// ==AzureaScript==
// @name AzureaVim
// @author http://c4se.sakura.ne.jp/profile.html
// @scriptUrl https://github.com/ne-sachirou/AzureaVim/raw/master/js/
// @date 2011-04-11
// @license MIT License
// ==/AzureaScript==
AzureaUtil={mixin:{},ApiProxy:{},db:{},retweet:{},favorite:{},event:{},time:{},template:{},yank:{},notify:{}};
(function(){function f(){return(this.getUTCFullYear()<1E3?this.getUTCFullYear()<100?this.getUTCFullYear()<10?"000":"00":"0":"")+this.getUTCFullYear()+"-"+(this.getUTCMonth()+1<10?"0":"")+(this.getUTCMonth()+1)+"-"+(this.getUTCDate()<10?"0":"")+this.getUTCDate()+"T"+(this.getUTCHours()<10?"0":"")+this.getUTCHours()+":"+(this.getUTCMinutes()<10?"0":"")+this.getUTCMinutes()+":"+(this.getUTCSeconds()<10?"0":"")+this.getUTCSeconds()+"Z"}function h(a,c,b){var e;if(b==null)b=true;for(e in c)if(b||typeof a[e]===
"undefined")a[e]=c[e]}function d(a){if(!(this instanceof d))return new d(a);a=a||"";this.uri=y+a;return this}function n(a,c){System.settings.setValue("user.AzureaVim",a,encodeURIComponent(c));x[a]=c}function j(a){x[a]||(x[a]=decodeURIComponent(System.settings.getValue("user.AzureaVim",a)));return x[a]}function k(a){for(var c=TwitterService.status.get(a),b=q.preCreateFavorite,e=q.postCreateFavorite,o=false,i=-1;b[++i];)o=b[i](c)||o;if(!o){TwitterService.favorite.create(a);for(i=-1;e[++i];)e[i](c)}}
function l(a){for(var c=TwitterService.status.get(a),b=q.preDestroyFavorite,e=q.postDestroyFavorite,o=false,i=-1;b[++i];)o=b[i](c)||o;if(!o){TwitterService.favorite.destroy(a);for(i=-1;e[++i];)e[i](c)}}function m(a){for(var c=TwitterService.status.get(a),b=B.preCreateRetweet,e=B.postCreateRetweet,o=false,i=-1;b[++i];)o=b[i](c)||o;if(!o){TwitterService.retweet.create(a);for(i=-1;e[++i];)e[i](c)}}function g(a,c){System.isActive?System.showNotice(c):System.showMessage(a,c,1048576)}function s(a,c,b,e){a=
{title:a,text:c,sticky:e?"on":null};a[/^https?:\/\/./.test(b)?"icon_uri":"twitter_screen_name"]=b;F.submit(null,a,function(o){try{var i=JSON.parse(o.body);i.error&&g(null,i.request.text)}catch(p){g(null,p.message+o.body)}})}Array.isArray||(Array.isArray=function(a){return Object.prototype.toString.call(a)==="[object Array]"});Array.prototype.every||(Array.prototype.every=function(a,c){for(var b=this.length;b--;)if(typeof this[b]!=="undefined"&&!a.call(c,this[b],b,this))return false;return true});
Array.prototype.filter||(Array.prototype.filter=function(a,c){for(var b=[],e=0,o=this.length;e<o;++e)typeof this[e]!=="undefined"&&a.call(c,this[e],e,this)&&b.push(this[e]);return b});Array.prototype.forEach||(Array.prototype.forEach=function(a,c){for(var b=this.length;b--;)typeof this[b]!=="undefined"&&a.call(c,this[b],b,this);return this});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,c){var b,e=this.length;for(c=c||0;c<0;)c+=e-1;for(b=c;b<e;++b)if(this[b]===a)return b;return-1});
Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(a,c){var b;b=this.length;if(typeof c==="undefined")c=b-1;for(;c<0;)c+=b-1;for(b=c;b>=0;--b)if(this[b]===a)return b;return-1});Array.prototype.map||(Array.prototype.map=function(a,c){for(var b=this.length,e=Array(b);b--;)if(typeof this[b]!=="undefined")e[b]=a.call(c,this[b],b,this);return e});Array.prototype.reduce||(Array.prototype.reduce=function(a,c){var b=0,e=this.length;if(typeof c==="undefined"){c=this[0];b=1}for(;b<e;++b)if(typeof this[b]!==
"undefined")c=a.call(null,c,this[b],b,this);return c});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(a,c){var b=this.length;if(typeof c!=="undefined"){c=this[b];--b}for(;b--;)if(typeof this[b]!=="undefined")c=a.call(null,c,this[b],b,this);return c});Array.prototype.some||(Array.prototype.some=function(a,c){for(var b=this.length;b--;)if(typeof this[b]!=="undefined"&&a.call(c,this[b],b,this))return true;return false});String.prototype.trim||(String.prototype.trim=function(){for(var a=
this.replace(/^\s\s*/,""),c=/\s/,b=a.length;c.test(a.charAt(--b)););return a.slice(0,b+1)});Object.keys||(Object.keys=function(a){var c,b=[];for(c in a)a.hasOwnProperty(c)&&b.push(c);return b});Date.now||(Date.now=function(){return(new Date).getTime()});Date.prototype.toISOString||(Date.prototype.toISOString=f);JSON={};(function(){function a(t){return t<10?"0"+t:t}function c(t){o.lastIndex=0;return o.test(t)?'"'+t.replace(o,function(D){var v=u[D];return typeof v==="string"?v:"\\u"+("0000"+D.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+t+'"'}function b(t,D){var v,A,E,I,G=i,C,r=D[t];if(r&&typeof r==="object"&&typeof r.toJSON==="function")r=r.toJSON(t);if(typeof z==="function")r=z.call(D,t,r);switch(typeof r){case "string":return c(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";i+=p;C=[];if(Object.prototype.toString.apply(r)==="[object Array]"){I=r.length;for(v=0;v<I;v+=1)C[v]=b(v,r)||"null";E=C.length===0?"[]":i?"[\n"+i+C.join(",\n"+i)+"\n"+
G+"]":"["+C.join(",")+"]";i=G;return E}if(z&&typeof z==="object"){I=z.length;for(v=0;v<I;v+=1)if(typeof z[v]==="string"){A=z[v];if(E=b(A,r))C.push(c(A)+(i?": ":":")+E)}}else for(A in r)if(Object.prototype.hasOwnProperty.call(r,A))if(E=b(A,r))C.push(c(A)+(i?": ":":")+E);E=C.length===0?"{}":i?"{\n"+i+C.join(",\n"+i)+"\n"+G+"}":"{"+C.join(",")+"}";i=G;return E}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+
1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,o=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,p,u={"\u0008":"\\b","\t":"\\t","\n":"\\n",
"\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},z;if(typeof JSON.stringify!=="function")JSON.stringify=function(t,D,v){var A;p=i="";if(typeof v==="number")for(A=0;A<v;A+=1)p+=" ";else if(typeof v==="string")p=v;if((z=D)&&typeof D!=="function"&&(typeof D!=="object"||typeof D.length!=="number"))throw Error("JSON.stringify");return b("",{"":t})};if(typeof JSON.parse!=="function")JSON.parse=function(t,D){function v(E,I){var G,C,r=E[I];if(r&&typeof r==="object")for(G in r)if(Object.prototype.hasOwnProperty.call(r,
G)){C=v(r,G);if(C!==undefined)r[G]=C;else delete r[G]}return D.call(E,I,r)}var A;t=String(t);e.lastIndex=0;if(e.test(t))t=t.replace(e,function(E){return"\\u"+("0000"+E.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(t.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){A=eval("("+t+")");return typeof D==="function"?v({"":A},""):A}throw new SyntaxError("JSON.parse");}})();
AzureaUtil.mixin=h;var y="http://localhost:80/",w={ready:[]};d.prototype={submit:function(a,c,b){var e,o=this.uri,i=[],p;for(p in c)c.hasOwnProperty(p)&&c[p]&&i.push(p+"="+c[p]);i=encodeURI(i.join("&"));a=(a=a||"")?/\/$/.test(o)&&a.charAt(0)==="/"?o.substring(1)+a:!/\/$/.test(o)&&a.charAt(0)!=="/"?o+"/"+a:o+a:o;if(b&&c)Http.postRequestAsync(a,i,false,b);else if(b)Http.sendRequestAsync(a,false,b);else e=c?Http.postRequest(a,i,false):Http.sendRequest(a,false);return e}};(function(){function a(c){var b;
if(200<=c.statusCode&&c.statusCode<300){c=w.ready;for(b=c.length;b--;)c[b]();w.ready=[]}else System.setTimeout(function(){Http.sendRequestAsync(y,false,a)},100)}Http.sendRequestAsync(y,false,a)})();AzureaUtil.ApiProxy=d;h(AzureaUtil.ApiProxy,{addEventListener:function(a,c){var b=w[a],e=b.length;if(b){for(;e--;)b[e]===c&&b.splice(e,1);b.push(c)}},removeEventListener:function(a,c){for(var b=w[a],e=b.length;e--;)if(b[e]===c){b.splice(e,1);break}}});var x={};h(AzureaUtil.db,{get:j,set:n,del:function(a){System.settings.setValue("user.AzureaVim",
a,"");delete x[a]},keys:function(){var a,c=[];for(a in x)match.test(a)&&c.push(a);return c}});var q={preCreateFavorite:[],postCreateFavorite:[],preDestroyFavorite:[],postDestroyFavorite:[]};System.addKeyBindingHandler(70,0,function(a){TwitterService.status.get(a).favorited?l(a):k(a)});h(AzureaUtil.favorite,{addEventListener:function(a,c){var b=q[a],e=-1;if(b){for(;b[++e];)b[e]===c&&b.splice(e,1);b.push(c)}},removeEventListener:function(a,c){for(var b=q[a],e=-1;b[++e];)if(b[e]===c){b.splice(e,1);break}},
create:k,destroy:l});var B={preCreateRetweet:[],postCreateRetweet:[]};System.addKeyBindingHandler(84,0,function(a){var c=TwitterService.status.get(a);if(System.settings.getValue("Misc","UseQT")){TextArea.text="RT @"+c.user.screen_name+": "+c.text;TextArea.show();TextArea.setFocus()}else System.showMessage("\u9078\u629e\u9805\u76ee\u3092\u30ea\u30c4\u30a4\u30fc\u30c8\u3057\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f","\u78ba\u8a8d",4)===6&&m(a)});System.addKeyBindingHandler(87,
0,function(a){var c=TwitterService.status.get(a);if(System.settings.getValue("Misc","UseQT"))System.showMessage("\u9078\u629e\u9805\u76ee\u3092\u30ea\u30c4\u30a4\u30fc\u30c8\u3057\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f","\u78ba\u8a8d",4)===6&&m(a);else{TextArea.text="RT @"+c.user.screen_name+": "+c.text;TextArea.show();TextArea.setFocus()}});h(AzureaUtil.retweet,{addEventListener:function(a,c){var b=B[a],e=-1;if(b){for(;b[++e];)b[e]===c&&b.splice(e,1);b.push(c)}},removeEventListener:function(a,
c){for(var b=B[a],e=-1;b[++e];)if(b[e]===c){b.splice(e,1);break}},create:m});var H={};h(AzureaUtil.time,{setTimeout:function(a,c){return System.setTimeout(a,c)},clearTimeout:function(a){return System.clearTimeout(a)},setInterval:function(a,c){var b;b=System.setTimeout(function(){if(H[b]){a();System.setTimeout(a,c)}},c);H[b]=true;return b},clearInterval:function(a){delete timeinterval_list[a]}});h(AzureaUtil.template,{expand:function(a,c){function b(p){var u,z,t;if(typeof p==="string"||p instanceof
String)u='"'+p.replace('"','\\"')+'"';else if(typeof p==="number"||p instanceof Number)u=p.toString(10);else if(p===true||p===false)u=p;else if(p===null)u="null";else if(typeof p==="undefined")u="void(0)";else if(p instanceof Array){u="[";z=0;for(t=p.length;z<t;++z)u+=b(p[z])+",";u=u.replace(/,$/,"")+"]"}else{u="{";for(z in p)if(p.hasOwnProperty(z))u+='"'+z+'":'+b(p[z])+",";u=u.replace(/,$/,"")+"}"}return u}var e,o=function(){var p,u="";for(p in c)if(c.hasOwnProperty(p))u+="var "+p+"="+b(c[p])+";";
return u}(),i=a.replace(/#{([^}]+?)}/g,function(p,u){return eval("(function(){"+o+"return ("+u+")})()")});i=i.split("#{}");if(i.length===1){e=0;i=i[0]}else{e=i[0].length;i=i.join("")}return{text:i,cursor:e}}});h(AzureaUtil.yank,{get:function(a){if(a){a=a.charAt(0);if(/[0-9A-Za-z]/.test(a))a=""}else a="";return j("Yank"+a)},set:function(a,c){if(a){a=a.charAt(0);if(/[0-9A-Za-z]/.test(a))a=""}else a="";n("Yank"+a,c);return c}});var F=new d("gntp");j("NotifyUseGrowl")||n("NotifyUseGrowl","0");AzureaUtil.notify=
function(a,c,b,e){var o=System.systemInfo<=2&&j("NotifyUseGrowl")!=="0";try{o?s(c,a,b,e):g(c,a)}catch(i){g(c,a)}}})();AzureaVim={};
(function(){function f(j){var k=System.inputBox("command","",true),l=System.views.currentView;n=l.getItem(l.selectedItemId);AzureaUtil.yank.set(null,k);(new h({text:":"+k,in_reply_to_status_id:j||l.selectedStatusId})).run()}function h(j){var k=TwitterService.status,l=j.in_reply_to_status_id,m=k.get(l);this.item=n;j=this.command_text=j.text.slice(1);var g=[],s,y=/[^\s"]+|\s+|"[^\\"]*(?:\\.[^\\"]*)*"/g;for(j=j.replace(/^\s+|\s+$/g,"");s=y.exec(j);)/^\s/.test(s[0])||g.push(s[0].replace(/^"|"$/g,""));
this.command=g;this.status_id=l;this.user=m.user;this.screen_name=m.user.screen_name;this.status=m;this.status_text=m.text;this.status_urls=[];this.status_hashes=[];this.status_users=[];k.getUrls(l,this.status_urls);k.getHashes(l,this.status_hashes);k.getUsers(l,this.status_users)}var d={},n;System.addKeyBindingHandler(186,0,function(j){var k=System.views.currentView;n=k.getItem(k.selectedItemId);AzureaUtil.yank.set(null,TextArea.text);TextArea.text=":";TextArea.in_reply_to_status_id=j;TextArea.show();
TextArea.setFocus();TextArea.cursor=1});System.addKeyBindingHandler(186,2,f);System.addContextMenuHandler(":vim",0,f);TwitterService.addEventListener("preSendUpdateStatus",function(j){var k,l=false;try{if(j.text===":"){l=true;System.setTimeout(function(){TextArea.text=AzureaUtil.yank.get(null);TextArea.show()},10)}else if(/^(?::|\uff1a)/.test(j.text)){l=true;AzureaUtil.yank.set(null,j.text);k=new h(j);TextArea.text="";TextArea.in_reply_to_status_id=0;k.run()}else AzureaUtil.yank.set(null,j.text)}catch(m){System.alert(m.name+
":\n"+m.message);l=true}return l});AzureaVim=h;AzureaVim.commands_list=d;AzureaVim.prototype={run:function(){var j=this.command,k=d[this.command[0]];if(k){if(k.indexOf(" ")!==-1){j.shift();j=this.command=k.split(" ").concat(j);k=j[0]}this[k]()}else System.showNotice(":"+j[0]+" command is undefined.")}}})();AzureaUtil.mixin(AzureaVim.commands_list,{eval:"_evaluate"});
AzureaVim.prototype._evaluate=function(){this.command[1]=this.command.slice(1).join(" ");System.inputBox(this.command[1],eval(this.command[1]),false)};AzureaUtil.mixin(AzureaVim.commands_list,{unshorten:"unshorten","\u3046\u3093\u3057\u3087\uff52\u3066\uff4e":"unshorten"});
(function(){function f(g){j=g.body.split(", ");j.push("htn.to")}function h(g){for(var s=j,y=s.length,w=false;y--;)if(g.indexOf(s[y])!==-1){w=true;break}return w}function d(g,s){function y(c){x=(c=c.header.match(/Location: ([^\n]+)\n/))?c[1]:g;c=c?c[1]:g;return x[g]=c}function w(c){c=/^error/.test(c.body)?g:c.body;return x[g]=c}var x=k,q=g;if(x[g])q=x[g];else if(g.indexOf("htn.to")!==-1)if(s)try{Http.sendRequestAsync(g,false,y)}catch(B){}else try{q=callback_htly(Http.sendRequest(g,false))}catch(H){}else if(h(g))if(s)try{Http.sendRequestAsync("http://untiny.me/api/1.0/extract/?url="+
g+"&format=text",false,w)}catch(F){}else try{q=w(Http.sendRequest("http://untiny.me/api/1.0/extract/?url="+g+"&format=text",false))}catch(a){}return q}function n(g,s){function y(F){F=F.body.match(/<body>([\s\S]*?)<\/body>/m)[1];var a;if(a=F.match(/<!\[CDATA\[([\s\S]*?)\]\]>/m))F=a[1].replace(/<\/(?:p|div|blockquote)>/g,"\n").replace(/<[\s\S]+?>/mg,"");F+="\n"+g;return w[x]=F}var w=l,x=g.match(/^https?:\/\/post\.ly\/(.+)$/)[1],q=g;if(w[x])q=w[x];else if(s)try{Http.sendRequestAsync("http://posterous.com/api/getpost?id="+
x,false,y)}catch(B){}else try{q=y(Http.sendRequest("http://posterous.com/api/getpost?id="+x,false))}catch(H){}return q}var j=[],k={"http://c4se.tk/":"http://c4se.sakura.ne.jp/"},l={};try{Http.sendRequestAsync("http://untiny.me/api/1.0/services/?format=text",true,f)}catch(m){}TwitterService.addEventListener("preProcessTimelineStatus",function(g){g.text=g.text.replace(/https?:\/\/[0-9A-Za-z._\-^~\/&%?]+/g,function(s){return s.indexOf("post.ly")!==-1?n(s,true):d(s,true)})});AzureaVim.prototype.unshorten=
function(){var g=this.status_urls[this.command[1]||0];this.item.text=g.indexOf("post.ly")!==-1?this.status_text.replace(g,n(g,false)):this.status_text.replace(g,d(g,false))};AzureaVim.prototype.unshorten.unshorten=d})();AzureaUtil.mixin(AzureaVim.commands_list,{open:"open",o:"open","\u304a":"open",url:"open url","\u3046\uff52\uff4c":"open url"});
(function(){function f(){var d=f.c1[this.command[1]]?f.addresses[f.c1[this.command[1]]].call(this):this.status_urls[0]?this.status_urls[0]:"https://twitter.com/"+this.screen_name+"/status/"+this.status_id,n;d=h(d,true);(n=System.getPreviewUrl(d))?System.showPreview(d,n):System.openUrl(d)}var h=AzureaVim.prototype.unshorten?AzureaVim.prototype.unshorten.unshorten:function(d){return d};f.c1={status:"status",favstar:"favstar",fav:"favstar",f:"favstar",favotter:"favotter",favlook:"favlook",twistar:"twistar",
favolog:"favolog",twilog:"twilog",user:"user",u:"user",url:"url"};f.addresses={status:function(){return"https://twitter.com/"+this.screen_name+"/status/"+this.status_id},favstar:function(){return"http://favstar.fm/t/"+this.status_id},favotter:function(){return"http://favotter.net/status.php?id="+this.status_id},favlook:function(){return"http://favlook.osa-p.net/status.html?status_id="+this.status_id},twistar:function(){return"http://twistar.cc/"+this.screen_name+"/status/"+this.status_id},twilog:function(){return"http://twilog.org/"+
(this.command[2]||this.screen_name)},user:function(){return"http://twitter.com/"+(this.command[2]||this.screen_name)},url:function(){return this.status_urls[this.command[2]||0]}};AzureaVim.prototype.open=f;System.addKeyBindingHandler(190,0,function(d){TwitterService.status.update(":o",d)})})();AzureaUtil.mixin(AzureaVim.commands_list,{reply:"reply",r:"reply","\uff52":"reply","@":"reply","\uff20":"reply",quotetweet:"reply quote",qt:"reply quote","\uff51\uff54":"reply quote",mrt:"reply mrt","\uff4d\uff52\uff54":"reply mrt"});
(function(){function f(){function h(){TextArea.text=j.text;TextArea.in_reply_to_status_id=d===true?n:0;TextArea.show();TextArea.setFocus();TextArea.cursor=j.cursor}var d,n=this.status_id,j,k;if(this.command[1]==="template"){d=this.command[3]==="true";j=AzureaUtil.template.expand(this.command[2],this);System.setTimeout(h,10)}else{k=f.templates[f.c1[this.command[1]]]||["@#{screen_name} #{}#{status_hashes.length ? ' ' + status_hashes.join(' ') : ''}",true];if(typeof k==="function")k=k.call(this);this.command=
["reply","template",k[0],k[1]?"true":"false"];f.call(this)}}f.c1={template:"template",all:"all",quote:"quote",qt:"quote",mrt:"mrt",masirosiki:"mrt"};f.templates={all:["@#{screen_name + (status_users.length ? ' @' +status_users.join(' @') : '')} #{}",true],quote:["@#{screen_name} #{} RT: #{status_text}",true],mrt:function(){return this.command[2]==="f"||this.command[2]==="fav"||this.command[2]==="favstar"?["#{} MRT: #{'http://favstar.fm/t/' + status_id}",false]:["#{} MRT: #{'http://twitter.com/' + screen_name + '/status/' + status_id}",
false]}};AzureaVim.prototype.reply=f;System.addKeyBindingHandler(82,0,function(h){var d=TwitterService.status.get(h).user.screen_name,n=[];TwitterService.status.getHashes(h,n);TextArea.text="@"+d+" "+(n.length?" "+n.join(" "):"");TextArea.in_reply_to_status_id=h;TextArea.show();TextArea.setFocus();TextArea.cursor=d.length+2})})();AzureaUtil.mixin(AzureaVim.commands_list,{retweet:"retweet",rt:"retweet","\uff52\uff54":"retweet"});AzureaVim.prototype.retweet=function(){AzureaUtil.retweet.create(this.status_id)};
AzureaUtil.mixin(AzureaVim.commands_list,{settings:"settings",setting:"settings",set:"settings","\u305b\uff54":"settings",get:"settings","\u3052\uff54":"settings"});
AzureaVim.prototype.settings=function(){var f;f=this.command.slice(1).join("");f=f.split("::");f=[f[0]].concat(f[1].split("="));if(/^(?:get|\u3052\uff54)/.test(this.command[0]))f.length=2;if(f[2]){System.settings.setValue(f[0],f[1],f[2]);System.showNotice("Setting done: "+f[0]+"::"+f[1]+"="+f[2])}else System.showNotice("Getting done: "+f[0]+"::"+f[1]+"="+System.settings.getValue(f[0],f[1]))};AzureaUtil.mixin(AzureaVim.commands_list,{shindan:"shindanmaker","\u3057\u3093\u3060\uff4e":"shindanmaker"});
AzureaVim.prototype.shindanmaker=function(){for(var f,h=-1,d=this.unshorten?this.unshorten.unshorten:function(n){return n};f=d(this.status_urls[++h],true);)if(f.match("^http://shindanmaker.com/[0-9]+"))break;if(f)Http.postRequestAsync(f,"u="+encodeURI(this.command[1]||TwitterService.currentUser.screen_name),false,function(n){n.body.match("<textarea.*?>(.*?)</textarea>");TextArea.text=RegExp.$1;TextArea.in_reply_to_status_id=0;TextArea.show();TextArea.setFocus()})};
AzureaUtil.mixin(AzureaVim.commands_list,{translate:"translate",ja:"translate ja","\u3058\u3083":"translate ja"});
AzureaVim.prototype.translate=function(){var f=System.views.currentView,h=f.getItem(f.selectedItemId);this.command[1]||(this.command[1]="ja");Http.sendRequestAsync("https://www.googleapis.com/language/translate/v2?key=AIzaSyCva1yUIFIBRqXOZDJ0nrbGbm0bz3FIksc&q="+encodeURI(this.status_text)+"&target="+this.command[1],false,function(d){if(d.statusCode!==200)throw Error("Google Translate API Error. statusCode is "+d.statusCode+".");h.text=d.body.match(/"translatedText"\s*:\s*"(.*)"/)[1]})};
AzureaUtil.mixin(AzureaVim.commands_list,{view:"view",v:"view",home:"view home","\u307b\u3081":"view home",user:"view user","\u3046\u305b\uff52":"view user"});
AzureaVim.prototype.view=function(){switch(this.view.c1[this.command[1]]){case "home":System.views.openView(0);break;case "mention":System.views.openView(1);break;case "message":System.views.openView(2);break;case "user":System.views.openView(5,this.command[2]||this.screen_name);break;case "search":System.views.openView(4,this.command[2]);break;case "favorite":System.views.openView(3);break;case "match":System.views.openView(6,this.command[2]);break;case "following":System.views.openView(8);break;
case "followers":System.views.openView(9)}};AzureaVim.prototype.view.c1={home:"home",timeline:"home",h:"home",mention:"mention",reply:"mention",r:"mention",m:"mention","@":"mention",message:"message",dm:"message",d:"message",user:"user",u:"user",search:"search",favorite:"favorite",fav:"favorite",f:"favorite",match:"match",following:"following",follow:"following",followers:"followers",follower:"followers",followed:"followers"};
AzureaUtil.mixin(AzureaVim.commands_list,{earthquake:"earthquake",jisin:"earthquake","\u3048\u3042\uff52\uff54\uff48\u304f\u3042\u3051":"earthquake","\u3058\u3057\uff4e":"earthquake"});
(function(){function f(d){var n=AzureaUtil.db.get("EarthquakeMessage");if(d!=null)n=AzureaUtil.template.expand(n,d).text;return n}function h(d){d=d||AzureaUtil.db.get("EarthquakeMessage");AzureaUtil.db.set("EarthquakeMessage",d);return d}AzureaUtil.db.get("EarthquakeMessage")||AzureaUtil.db.set("EarthquakeMessage","\u5730\u9707\u306a\u3046 #{Date()}");AzureaVim.prototype.earthquake=function(){var d;switch(this.command[1]){case "set":if(this.command[2])d=h(this.command[2]);else{d=System.inputBox("\u5730\u9707\u306a\u3046\u6295\u7a3f\u6587",
f(),false);h(d);d=d}d=d;break;default:TwitterService.status.update(f(this),0)}return d};System.addKeyBindingHandler(40,2,function(){TwitterService.status.update(":earthquake",0)})})();AzureaUtil.mixin(AzureaVim.commands_list,{delay:"delay","\u3067\u3041\uff59":"delay"});
(function(){function f(h,d,n){Http.postRequestAsync("http://twitdelay.appspot.com/api/post","user_id="+TwitterService.currentUser.id+"&api_key="+AzureaUtil.db.get("DelayTwitDelayApiKey")+"&status="+h+"&at="+d,false,n)}AzureaUtil.db.get("DelayUseTwitDelay")&&AzureaUtil.db.set("DelayUseTwitDelay","0");AzureaVim.prototype.delay=function(){var h,d;if(h=this.command[1].match(/^(?:(?:(\d{4})-)?(\d{1,2})-(\d{1,2}) )?(\d{1,2}):(\d{1,2})(?::(\d{1,2}))?$/)){d=new Date;h[1]&&d.setFullYear(h[1]);h[2]&&d.setMonth(h[2]-
1);h[3]&&d.setDate(h[3]);d.setHours(h[4]);d.setMinutes(h[5]);d.setSeconds(0);h[6]&&d.setSeconds(h[6]);this.command[1]=d.getTime();h=2}else{this.command[1]=(new Date).getTime()+(this.command[1]-0);h=1}this.command[2]=this.command.slice(2).join(" ");if(AzureaUtil.db.get("DelayUseTwitDelay")){d=new Date(this.command[1]);f(this.command[2],d.getUTCDate()+" "+d.getUTCMonth()+" "+d.getUTCFullYear()+" "+d.getUTCHours()+":"+d.getUTCMinutes()+":"+d.getUTCSeconds()+" +0000",function(){})}else h===1?System.setTimeout(function(n){return function(){TwitterService.status.update(n.command[2],
n.status_id)}}(this),this.command[1]-(new Date).getTime()):AzureaUtil.time.setTimeevent('function() {TwitterService.status.update("'+this.command[2]+'", "'+this.status_id+'");}',this.command[1])}})();AzureaUtil.mixin(AzureaVim.codelist,{});System.addKeyBindingHandler(67,2,function(f){f=TwitterService.status.get(f).text;System.clipboard=f;AzureaUtil.yank.set(null,f)});AzureaUtil.mixin(AzureaVim.commands_list,{notify:"notify"});
(function(){function f(l,m){m=m||"";if(l){j=RegExp(l,m);AzureaUtil.db.set("NotifyPattern",l);AzureaUtil.db.set("NotifyPatternOption",m)}else j=null;return j}function h(){function l(s){var y,w=s.match(/^\/(.*)\/([a-zA-Z]*)$/);if(w){s=w[1];y=w[2].toLowerCase()}return[s,y]}var m,g;switch(h.c1[this.command[1]]){case "pattern":if(m=this.command.slice(2).join(" "))m=l(m);else{m=AzureaUtil.db.get("NotifyPattern");g=AzureaUtil.db.get("NotifyPatternOption");m=l(System.inputBox("tweet\u306b\u30de\u30c3\u30c1\u3055\u305b\u308b\u6b63\u898f\u8868\u73fe",
g?"/"+m+"/"+g:m,false))}g=m[1];m=m[0];f(m,g);break;case "when":m=h.c2[this.command[2]];if(!m)throw Error("plugins/notify: No such option as NotifyWhen "+this.command[2]);k[m]=(this.command[3]||System.inputBox("NotifyWhen"+m,k[m],true))==="0"?"0":"1";AzureaUtil.db.set("NotifyWhen"+m,k[m]);break;case "growl":AzureaUtil.db.set("NotifyUseGrowl",(this.command[2]||System.inputBox("NotifyUseGrowl",AzureaUtil.db.get("NotifyUseGrowl"),true))==="0"?"0":"1")}}var d=AzureaUtil.db.get("NotifyPattern"),n=AzureaUtil.db.get("NotifyPatternOption"),
j=null,k={Faved:AzureaUtil.db.get("NotifyWhenFaved"),Mention:AzureaUtil.db.get("NotifyWhenMention"),Matched:AzureaUtil.db.get("NotifyWhenMatched")};if(d)j=RegExp(d,n);h.c1={pattern:"pattern",when:"when",growl:"growl",gntp:"growl"};h.c2={faved:"Faved",fav:"Faved",f:"Faved",mention:"Mention",reply:"Mention",r:"Mention","@":"Mention",matched:"Matched",match:"Matched",m:"Matched"};AzureaVim.prototype.notify=h;TwitterService.addEventListener("receiveFavorite",function(l,m,g){k.Faved&&AzureaUtil.notify("Favs@"+
l.screen_name+": "+g.text,"Favs - AzureaVim",l.profile_image_url,false)});TwitterService.addEventListener("preFilterProcessTimelineStatus",function(l){var m=k,g=l.text;l=l.user;m.Mention&&g.indexOf(TwitterService.currentUser.screen_name)!==-1&&AzureaUtil.notify("Mention@"+l.screen_name+": "+g,"Mention - AzureaVim",l.profile_image_url,false);m.Matched&&j&&j.test(g)&&AzureaUtil.notify("Matches@"+l.screen_name+": "+g,"Matched - AzureaVim",l.profile_image_url,false)})})();
AzureaUtil.mixin(AzureaVim.commands_list,{tumblr:"tumblr","\u3064\uff4d\uff42\uff4c\uff52":"tumblr"});
(function(){function f(q,B){Http.postRequestAsync("https://www.tumblr.com/api/authenticate","email="+q+"&password="+B,false,function(H){g=200<=H.statusCode||H.statusCode<300?true:false})}function h(q,B,H,F,a,c){function b(e){var o,i=[];for(o in e)e.hasOwnProperty(o)&&i.push(o+"="+encodeURI(e[o]));return i.join("&")}Http.postRequestAsync("https://www.tumblr.com/api/write","email="+q+"&password="+B+"&type="+H+"&"+b(F)+(a?"&"+b(a):""),false,c)}function d(q){if(q.user.protected_)throw Error("plugins/tumblr: "+
q.user.screen_name+" is protected_.");else h(j,k,"quote",{quote:q.text,source:'<a href="http://twitter.com/'+q.user.screen_name+"/status/"+q.id+'">Twitter/@'+q.user.name+": </a>"},{generator:"AzureaVim",tags:m},function(B){if(B.statusCode<200&&300<=B.statusCode)throw Error("plugins/tumblr: Cannot create post. (statusCode="+B.statusCode+")");})}function n(){var q;switch(n.c1[this.command[1]]){case "when":q=n.c2[this.command[2]];if(!q)throw Error("plugins/tumblr: No such option as TumblrWhen "+this.command[2]);
l[q]=(this.command[3]||System.inputBox("TumblrWhen"+q,l[q],true))==="1"?"1":"0";AzureaUtil.db.set("TumblrWhen"+q,l[q]);l.Favorite==="1"?s("postCreateFavorite",d):y("postCreateFavorite",d);l.Retweet==="1"?w("postCreateRetweet",d):x("postCreateRetweet",d);break;case "email":j=this.command[2]||System.inputBox("TumblrEmail",j,true);AzureaUtil.db.set("TumblrEmail",j);f(j,k);break;case "password":k=this.command[2]||System.inputBox("TumblrPassword",k,true);AzureaUtil.db.set("TumblrPassword",k);f(j,k);break;
case "tags":m=this.command[2]||System.inputBox("TumblrTags",m,false);AzureaUtil.db.set("TumblrTags",m);break;default:if(!g)throw Error("plugins/tumblr: Authenticate your email & password.");d(this.status)}}var j=AzureaUtil.db.get("TumblrEmail"),k=AzureaUtil.db.get("TumblrPassword"),l={Favorite:AzureaUtil.db.get("TumblrWhenFavorite")||"0",Retweet:AzureaUtil.db.get("TumblrWhenRetweet")||"0"},m=AzureaUtil.db.get("TumblrTags"),g=false,s=AzureaUtil.favorite.addEventListener,y=AzureaUtil.favorite.removeEventListener,
w=AzureaUtil.retweet.addEventListener,x=AzureaUtil.retweet.removeEventListener;f(j,k);l.Favorite==="1"&&s("postCreateFavorite",d);l.Retweet==="1"&&w("postRetweetFavorite",d);n.c1={when:"when",email:"email",password:"password",tags:"tags",tag:"tags"};n.c2={favorite:"Favorite",fav:"Favorite",f:"Favorite",retweet:"Retweet",rt:"Retweet"};AzureaVim.prototype.tumblr=n})();
