// ==AzureaScript==
// @name AzureaVim
// @author http://c4se.sakura.ne.jp/profile.html
// @scriptUrl https://github.com/ne-sachirou/AzureaVim/raw/master/js/
// @date 2011-04-11
// @license MIT License
// ==/AzureaScript==
AzureaUtil={mixin:{},ApiProxy:{},db:{},retweet:{},favorite:{},event:{},time:{},template:{},yank:{},notify:{}};
(function(){function e(){return(this.getUTCFullYear()<1E3?this.getUTCFullYear()<100?this.getUTCFullYear()<10?"000":"00":"0":"")+this.getUTCFullYear()+"-"+(this.getUTCMonth()+1<10?"0":"")+(this.getUTCMonth()+1)+"-"+(this.getUTCDate()<10?"0":"")+this.getUTCDate()+"T"+(this.getUTCHours()<10?"0":"")+this.getUTCHours()+":"+(this.getUTCMinutes()<10?"0":"")+this.getUTCMinutes()+":"+(this.getUTCSeconds()<10?"0":"")+this.getUTCSeconds()+"Z"}function h(b,c,a){var f;if(a==null)a=true;for(f in c)if(a||typeof b[f]===
"undefined")b[f]=c[f]}function d(b,c){System.settings.setValue("user.AzureaVim",b,encodeURIComponent(c));j[b]=c}function n(b){j[b]||(j[b]=decodeURIComponent(System.settings.getValue("user.AzureaVim",b)));return j[b]}function k(b){for(var c=TwitterService.status.get(b),a=g.preCreateFavorite,f=g.postCreateFavorite,t=false,i=-1;a[++i];)t=a[i](c)||t;if(!t){TwitterService.favorite.create(b);for(i=-1;f[++i];)f[i](c)}}function m(b){for(var c=TwitterService.status.get(b),a=g.preDestroyFavorite,f=g.postDestroyFavorite,
t=false,i=-1;a[++i];)t=a[i](c)||t;if(!t){TwitterService.favorite.destroy(b);for(i=-1;f[++i];)f[i](c)}}function l(b){for(var c=TwitterService.status.get(b),a=s.preCreateRetweet,f=s.postCreateRetweet,t=false,i=-1;a[++i];)t=a[i](c)||t;if(!t){TwitterService.retweet.create(b);for(i=-1;f[++i];)f[i](c)}}Array.isArray||(Array.isArray=function(b){return Object.prototype.toString.call(b)==="[object Array]"});Array.prototype.every||(Array.prototype.every=function(b,c){for(var a=this.length;a--;)if(typeof this[a]!==
"undefined"&&!b.call(c,this[a],a,this))return false;return true});Array.prototype.filter||(Array.prototype.filter=function(b,c){for(var a=[],f=0,t=this.length;f<t;++f)typeof this[f]!=="undefined"&&b.call(c,this[f],f,this)&&a.push(this[f]);return a});Array.prototype.forEach||(Array.prototype.forEach=function(b,c){for(var a=this.length;a--;)typeof this[a]!=="undefined"&&b.call(c,this[a],a,this);return this});Array.prototype.indexOf||(Array.prototype.indexOf=function(b,c){var a,f=this.length;for(c=c||
0;c<0;)c+=f-1;for(a=c;a<f;++a)if(this[a]===b)return a;return-1});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(b,c){var a;a=this.length;if(typeof c==="undefined")c=a-1;for(;c<0;)c+=a-1;for(a=c;a>=0;--a)if(this[a]===b)return a;return-1});Array.prototype.map||(Array.prototype.map=function(b,c){for(var a=this.length,f=Array(a);a--;)if(typeof this[a]!=="undefined")f[a]=b.call(c,this[a],a,this);return f});Array.prototype.reduce||(Array.prototype.reduce=function(b,c){var a=0,f=this.length;
if(typeof c==="undefined"){c=this[0];a=1}for(;a<f;++a)if(typeof this[a]!=="undefined")c=b.call(null,c,this[a],a,this);return c});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(b,c){var a=this.length;if(typeof c!=="undefined"){c=this[a];--a}for(;a--;)if(typeof this[a]!=="undefined")c=b.call(null,c,this[a],a,this);return c});Array.prototype.some||(Array.prototype.some=function(b,c){for(var a=this.length;a--;)if(typeof this[a]!=="undefined"&&b.call(c,this[a],a,this))return true;return false});
String.prototype.trim||(String.prototype.trim=function(){for(var b=this.replace(/^\s\s*/,""),c=/\s/,a=b.length;c.test(b.charAt(--a)););return b.slice(0,a+1)});Object.keys||(Object.keys=function(b){var c,a=[];for(c in b)b.hasOwnProperty(c)&&a.push(c);return a});Date.now||(Date.now=function(){return(new Date).getTime()});Date.prototype.toISOString||(Date.prototype.toISOString=e);JSON={};(function(){function b(r){return r<10?"0"+r:r}function c(r){t.lastIndex=0;return t.test(r)?'"'+r.replace(t,function(w){var u=
o[w];return typeof u==="string"?u:"\\u"+("0000"+w.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+r+'"'}function a(r,w){var u,y,A,C,B=i,z,q=w[r];if(q&&typeof q==="object"&&typeof q.toJSON==="function")q=q.toJSON(r);if(typeof v==="function")q=v.call(w,r,q);switch(typeof q){case "string":return c(q);case "number":return isFinite(q)?String(q):"null";case "boolean":case "null":return String(q);case "object":if(!q)return"null";i+=p;z=[];if(Object.prototype.toString.apply(q)==="[object Array]"){C=q.length;
for(u=0;u<C;u+=1)z[u]=a(u,q)||"null";A=z.length===0?"[]":i?"[\n"+i+z.join(",\n"+i)+"\n"+B+"]":"["+z.join(",")+"]";i=B;return A}if(v&&typeof v==="object"){C=v.length;for(u=0;u<C;u+=1)if(typeof v[u]==="string"){y=v[u];if(A=a(y,q))z.push(c(y)+(i?": ":":")+A)}}else for(y in q)if(Object.prototype.hasOwnProperty.call(q,y))if(A=a(y,q))z.push(c(y)+(i?": ":":")+A);A=z.length===0?"{}":i?"{\n"+i+z.join(",\n"+i)+"\n"+B+"}":"{"+z.join(",")+"}";i=B;return A}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=
function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,t=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
i,p,o={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;if(typeof JSON.stringify!=="function")JSON.stringify=function(r,w,u){var y;p=i="";if(typeof u==="number")for(y=0;y<u;y+=1)p+=" ";else if(typeof u==="string")p=u;if((v=w)&&typeof w!=="function"&&(typeof w!=="object"||typeof w.length!=="number"))throw Error("JSON.stringify");return a("",{"":r})};if(typeof JSON.parse!=="function")JSON.parse=function(r,w){function u(A,C){var B,z,q=A[C];if(q&&typeof q==="object")for(B in q)if(Object.prototype.hasOwnProperty.call(q,
B)){z=u(q,B);if(z!==undefined)q[B]=z;else delete q[B]}return w.call(A,C,q)}var y;r=String(r);f.lastIndex=0;if(f.test(r))r=r.replace(f,function(A){return"\\u"+("0000"+A.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(r.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){y=eval("("+r+")");return typeof w==="function"?u({"":y},""):y}throw new SyntaxError("JSON.parse");}})();
AzureaUtil.mixin=h;var j={};h(AzureaUtil.db,{get:n,set:d,del:function(b){System.settings.setValue("user.AzureaVim",b,"");delete j[b]},keys:function(){var b,c=[];for(b in j)match.test(b)&&c.push(b);return c}});var g={preCreateFavorite:[],postCreateFavorite:[],preDestroyFavorite:[],postDestroyFavorite:[]};System.addKeyBindingHandler(70,0,function(b){TwitterService.status.get(b).favorited?m(b):k(b)});h(AzureaUtil.favorite,{addEventListener:function(b,c){var a=g[b],f=-1;if(a){for(;a[++f];)a[f]===c&&a.splice(f,
1);a.push(c)}},removeEventListener:function(b,c){for(var a=g[b],f=-1;a[++f];)if(a[f]===c){a.splice(f,1);break}},create:k,destroy:m});var s={preCreateRetweet:[],postCreateRetweet:[]};System.addKeyBindingHandler(84,0,function(b){var c=TwitterService.status.get(b);if(System.settings.getValue("Misc","UseQT")){TextArea.text="RT @"+c.user.screen_name+": "+c.text;TextArea.show();TextArea.setFocus()}else System.showMessage("\u9078\u629e\u9805\u76ee\u3092\u30ea\u30c4\u30a4\u30fc\u30c8\u3057\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f",
"\u78ba\u8a8d",4)===6&&l(b)});System.addKeyBindingHandler(87,0,function(b){var c=TwitterService.status.get(b);if(System.settings.getValue("Misc","UseQT"))System.showMessage("\u9078\u629e\u9805\u76ee\u3092\u30ea\u30c4\u30a4\u30fc\u30c8\u3057\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f","\u78ba\u8a8d",4)===6&&l(b);else{TextArea.text="RT @"+c.user.screen_name+": "+c.text;TextArea.show();TextArea.setFocus()}});h(AzureaUtil.retweet,{addEventListener:function(b,c){var a=s[b],f=-1;
if(a){for(;a[++f];)a[f]===c&&a.splice(f,1);a.push(c)}},removeEventListener:function(b,c){for(var a=s[b],f=-1;a[++f];)if(a[f]===c){a.splice(f,1);break}},create:l});var x={};h(AzureaUtil.time,{setTimeout:function(b,c){return System.setTimeout(b,c)},clearTimeout:function(b){return System.clearTimeout(b)},setInterval:function(b,c){var a;a=System.setTimeout(function(){if(x[a]){b();System.setTimeout(b,c)}},c);x[a]=true;return a},clearInterval:function(b){delete timeinterval_list[b]}});h(AzureaUtil.template,
{expand:function(b,c){function a(p){var o,v,r;if(typeof p==="string"||p instanceof String)o='"'+p.replace('"','\\"')+'"';else if(typeof p==="number"||p instanceof Number)o=p.toString(10);else if(p===true||p===false)o=p;else if(p===null)o="null";else if(typeof p==="undefined")o="void(0)";else if(p instanceof Array){o="[";v=0;for(r=p.length;v<r;++v)o+=a(p[v])+",";o=o.replace(/,$/,"")+"]"}else{o="{";for(v in p)if(p.hasOwnProperty(v))o+='"'+v+'":'+a(p[v])+",";o=o.replace(/,$/,"")+"}"}return o}var f,t=
function(){var p,o="";for(p in c)if(c.hasOwnProperty(p))o+="var "+p+"="+a(c[p])+";";return o}(),i=b.replace(/#{([^}]+?)}/g,function(p,o){return eval("(function(){"+t+"return ("+o+")})()")});i=i.split("#{}");if(i.length===1){f=0;i=i[0]}else{f=i[0].length;i=i.join("")}return{text:i,cursor:f}}});h(AzureaUtil.yank,{get:function(b){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=""}else b="";return n("Yank"+b)},set:function(b,c){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=""}else b="";d("Yank"+b,c);
return c}});AzureaUtil.notify=function(b,c){try{System.isActive?System.showNotice(b):System.showMessage(c,b,1048576)}catch(a){System.isActive?System.showNotice(b):System.showMessage(c,b,1048576)}}})();AzureaVim={};
(function(){function e(k){var m=System.inputBox("command","",true),l=System.views.currentView;n=l.getItem(l.selectedItemId);AzureaUtil.yank.set(null,m);(new h({text:":"+m,in_reply_to_status_id:k||l.selectedStatusId})).run()}function h(k){var m=TwitterService.status,l=k.in_reply_to_status_id,j=m.get(l);this.item=n;k=this.command_text=k.text.slice(1);var g=[],s,x=/[^\s"]+|\s+|"[^\\"]*(?:\\.[^\\"]*)*"/g;for(k=k.replace(/^\s+|\s+$/g,"");s=x.exec(k);)/^\s/.test(s[0])||g.push(s[0].replace(/^"|"$/g,""));
this.command=g;this.status_id=l;this.user=j.user;this.screen_name=j.user.screen_name;this.status=j;this.status_text=j.text;this.status_urls=[];this.status_hashes=[];this.status_users=[];m.getUrls(l,this.status_urls);m.getHashes(l,this.status_hashes);m.getUsers(l,this.status_users)}var d={},n;System.addKeyBindingHandler(186,0,function(k){var m=System.views.currentView;n=m.getItem(m.selectedItemId);AzureaUtil.yank.set(null,TextArea.text);TextArea.text=":";TextArea.in_reply_to_status_id=k;TextArea.show();
TextArea.setFocus();TextArea.cursor=1});System.addKeyBindingHandler(186,2,e);System.addContextMenuHandler(":vim",0,e);TwitterService.addEventListener("preSendUpdateStatus",function(k){var m,l=false;try{if(k.text===":"){l=true;System.setTimeout(function(){TextArea.text=AzureaUtil.yank.get(null);TextArea.show()},10)}else if(/^(?::|\uff1a)/.test(k.text)){l=true;AzureaUtil.yank.set(null,k.text);m=new h(k);TextArea.text="";TextArea.in_reply_to_status_id=0;m.run()}else AzureaUtil.yank.set(null,k.text)}catch(j){System.alert(j.name+
":\n"+j.message);l=true}return l});AzureaVim=h;AzureaVim.commands_list=d;AzureaVim.prototype={run:function(){var k=this.command,m=d[this.command[0]];if(m){if(m.indexOf(" ")!==-1){k.shift();k=this.command=m.split(" ").concat(k);m=k[0]}this[m]()}else System.showNotice(":"+k[0]+" command is undefined.")}}})();AzureaUtil.mixin(AzureaVim.commands_list,{unshorten:"unshorten","\u3046\u3093\u3057\u3087\uff52\u3066\uff4e":"unshorten"});
(function(){function e(g){k=g.body.split(", ");k.push("htn.to")}function h(g){for(var s=k,x=s.length,b=false;x--;)if(g.indexOf(s[x])!==-1){b=true;break}return b}function d(g,s){function x(o){c=(o=o.header.match(/Location: ([^\n]+)\n/))?o[1]:g;o=o?o[1]:g;return c[g]=o}function b(o){o=/^error/.test(o.body)?g:o.body;return c[g]=o}var c=m,a=g;if(c[g])a=c[g];else if(g.indexOf("htn.to")!==-1)if(s)try{Http.sendRequestAsync(g,false,x)}catch(f){}else try{a=callback_htly(Http.sendRequest(g,false))}catch(t){}else if(h(g))if(s)try{Http.sendRequestAsync("http://untiny.me/api/1.0/extract/?url="+
g+"&format=text",false,b)}catch(i){}else try{a=b(Http.sendRequest("http://untiny.me/api/1.0/extract/?url="+g+"&format=text",false))}catch(p){}return a}function n(g,s){function x(i){i=i.body.match(/<body>([\s\S]*?)<\/body>/m)[1];var p;if(p=i.match(/<!\[CDATA\[([\s\S]*?)\]\]>/m))i=p[1].replace(/<\/(?:p|div|blockquote)>/g,"\n").replace(/<[\s\S]+?>/mg,"");i+="\n"+g;return b[c]=i}var b=l,c=g.match(/^https?:\/\/post\.ly\/(.+)$/)[1],a=g;if(b[c])a=b[c];else if(s)try{Http.sendRequestAsync("http://posterous.com/api/getpost?id="+
c,false,x)}catch(f){}else try{a=x(Http.sendRequest("http://posterous.com/api/getpost?id="+c,false))}catch(t){}return a}var k=[],m={"http://c4se.tk/":"http://c4se.sakura.ne.jp/"},l={};try{Http.sendRequestAsync("http://untiny.me/api/1.0/services/?format=text",true,e)}catch(j){}TwitterService.addEventListener("preProcessTimelineStatus",function(g){g.text=g.text.replace(/https?:\/\/[0-9A-Za-z._\-^~\/&%?]+/g,function(s){return s.indexOf("post.ly")!==-1?n(s,true):d(s,true)})});AzureaVim.prototype.unshorten=
function(){var g=this.status_urls[this.command[1]||0];this.item.text=g.indexOf("post.ly")!==-1?this.status_text.replace(g,n(g,false)):this.status_text.replace(g,d(g,false))};AzureaVim.prototype.unshorten.unshorten=d})();AzureaUtil.mixin(AzureaVim.commands_list,{open:"open",o:"open","\u304a":"open",url:"open url","\u3046\uff52\uff4c":"open url"});
(function(){function e(){var d=e.c1[this.command[1]]?e.addresses[e.c1[this.command[1]]].call(this):this.status_urls[0]?this.status_urls[0]:"https://twitter.com/"+this.screen_name+"/status/"+this.status_id,n;d=h(d,true);(n=System.getPreviewUrl(d))?System.showPreview(d,n):System.openUrl(d)}var h=AzureaVim.prototype.unshorten?AzureaVim.prototype.unshorten.unshorten:function(d){return d};e.c1={status:"status",favstar:"favstar",fav:"favstar",f:"favstar",favotter:"favotter",favlook:"favlook",twistar:"twistar",
favolog:"favolog",twilog:"twilog",user:"user",u:"user",url:"url"};e.addresses={status:function(){return"https://twitter.com/"+this.screen_name+"/status/"+this.status_id},favstar:function(){return"http://favstar.fm/t/"+this.status_id},favotter:function(){return"http://favotter.net/status.php?id="+this.status_id},favlook:function(){return"http://favlook.osa-p.net/status.html?status_id="+this.status_id},twistar:function(){return"http://twistar.cc/"+this.screen_name+"/status/"+this.status_id},twilog:function(){return"http://twilog.org/"+
(this.command[2]||this.screen_name)},user:function(){return"http://twitter.com/"+(this.command[2]||this.screen_name)},url:function(){return this.status_urls[this.command[2]||0]}};AzureaVim.prototype.open=e;System.addKeyBindingHandler(190,0,function(d){TwitterService.status.update(":o",d)})})();AzureaUtil.mixin(AzureaVim.commands_list,{reply:"reply",r:"reply","\uff52":"reply","@":"reply","\uff20":"reply",quotetweet:"reply quote",qt:"reply quote","\uff51\uff54":"reply quote",mrt:"reply mrt","\uff4d\uff52\uff54":"reply mrt"});
(function(){function e(){function h(){TextArea.text=k.text;TextArea.in_reply_to_status_id=d===true?n:0;TextArea.show();TextArea.setFocus();TextArea.cursor=k.cursor}var d,n=this.status_id,k,m;if(this.command[1]==="template"){d=this.command[3]==="true";k=AzureaUtil.template.expand(this.command[2],this);System.setTimeout(h,10)}else{m=e.templates[e.c1[this.command[1]]]||["@#{screen_name} #{}#{status_hashes.length ? ' ' + status_hashes.join(' ') : ''}",true];if(typeof m==="function")m=m.call(this);this.command=
["reply","template",m[0],m[1]?"true":"false"];e.call(this)}}e.c1={template:"template",all:"all",quote:"quote",qt:"quote",mrt:"mrt",masirosiki:"mrt"};e.templates={all:["@#{screen_name + (status_users.length ? ' @' +status_users.join(' @') : '')} #{}",true],quote:["@#{screen_name} #{} RT: #{status_text}",true],mrt:function(){return this.command[2]==="f"||this.command[2]==="fav"||this.command[2]==="favstar"?["#{} MRT: #{'http://favstar.fm/t/' + status_id}",false]:["#{} MRT: #{'http://twitter.com/' + screen_name + '/status/' + status_id}",
false]}};AzureaVim.prototype.reply=e;System.addKeyBindingHandler(82,0,function(h){var d=TwitterService.status.get(h).user.screen_name,n=[];TwitterService.status.getHashes(h,n);TextArea.text="@"+d+" "+(n.length?" "+n.join(" "):"");TextArea.in_reply_to_status_id=h;TextArea.show();TextArea.setFocus();TextArea.cursor=d.length+2})})();AzureaUtil.mixin(AzureaVim.commands_list,{retweet:"retweet",rt:"retweet","\uff52\uff54":"retweet"});AzureaVim.prototype.retweet=function(){AzureaUtil.retweet.create(this.status_id)};
AzureaUtil.mixin(AzureaVim.commands_list,{settings:"settings",setting:"settings",set:"settings","\u305b\uff54":"settings",get:"settings","\u3052\uff54":"settings"});
AzureaVim.prototype.settings=function(){var e;e=this.command.slice(1).join("");e=e.split("::");e=[e[0]].concat(e[1].split("="));if(/^(?:get|\u3052\uff54)/.test(this.command[0]))e.length=2;if(e[2]){System.settings.setValue(e[0],e[1],e[2]);System.showNotice("Setting done: "+e[0]+"::"+e[1]+"="+e[2])}else System.showNotice("Getting done: "+e[0]+"::"+e[1]+"="+System.settings.getValue(e[0],e[1]))};AzureaUtil.mixin(AzureaVim.commands_list,{shindan:"shindanmaker","\u3057\u3093\u3060\uff4e":"shindanmaker"});
AzureaVim.prototype.shindanmaker=function(){for(var e,h=-1,d=this.unshorten?this.unshorten.unshorten:function(n){return n};e=d(this.status_urls[++h],true);)if(e.match("^http://shindanmaker.com/[0-9]+"))break;if(e)Http.postRequestAsync(e,"u="+encodeURI(this.command[1]||TwitterService.currentUser.screen_name),false,function(n){n.body.match("<textarea.*?>(.*?)</textarea>");TextArea.text=RegExp.$1;TextArea.in_reply_to_status_id=0;TextArea.show();TextArea.setFocus()})};
AzureaUtil.mixin(AzureaVim.commands_list,{translate:"translate",ja:"translate ja","\u3058\u3083":"translate ja"});
AzureaVim.prototype.translate=function(){var e=System.views.currentView,h=e.getItem(e.selectedItemId);this.command[1]||(this.command[1]="ja");Http.sendRequestAsync("https://www.googleapis.com/language/translate/v2?key=AIzaSyCva1yUIFIBRqXOZDJ0nrbGbm0bz3FIksc&q="+encodeURI(this.status_text)+"&target="+this.command[1],false,function(d){if(d.statusCode!==200)throw Error("Google Translate API Error. statusCode is "+d.statusCode+".");h.text=d.body.match(/"translatedText"\s*:\s*"(.*)"/)[1]})};
AzureaUtil.mixin(AzureaVim.commands_list,{view:"view",v:"view",home:"view home","\u307b\u3081":"view home",user:"view user","\u3046\u305b\uff52":"view user"});
AzureaVim.prototype.view=function(){switch(this.view.c1[this.command[1]]){case "home":System.views.openView(0);break;case "mention":System.views.openView(1);break;case "message":System.views.openView(2);break;case "user":System.views.openView(5,this.command[2]||this.screen_name);break;case "search":System.views.openView(4,this.command[2]);break;case "favorite":System.views.openView(3);break;case "match":System.views.openView(6,this.command[2]);break;case "following":System.views.openView(8);break;
case "followers":System.views.openView(9)}};AzureaVim.prototype.view.c1={home:"home",timeline:"home",h:"home",mention:"mention",reply:"mention",r:"mention",m:"mention","@":"mention",message:"message",dm:"message",d:"message",user:"user",u:"user",search:"search",favorite:"favorite",fav:"favorite",f:"favorite",match:"match",following:"following",follow:"following",followers:"followers",follower:"followers",followed:"followers"};
AzureaUtil.mixin(AzureaVim.commands_list,{earthquake:"earthquake",jisin:"earthquake","\u3048\u3042\uff52\uff54\uff48\u304f\u3042\u3051":"earthquake","\u3058\u3057\uff4e":"earthquake"});
(function(){function e(d){var n=AzureaUtil.db.get("EarthquakeMessage");if(d!=null)n=AzureaUtil.template.expand(n,d).text;return n}function h(d){d=d||AzureaUtil.db.get("EarthquakeMessage");AzureaUtil.db.set("EarthquakeMessage",d);return d}AzureaUtil.db.get("EarthquakeMessage")||AzureaUtil.db.set("EarthquakeMessage","\u5730\u9707\u306a\u3046 #{Date()}");AzureaVim.prototype.earthquake=function(){var d;switch(this.command[1]){case "set":if(this.command[2])d=h(this.command[2]);else{d=System.inputBox("\u5730\u9707\u306a\u3046\u6295\u7a3f\u6587",
e(),false);h(d);d=d}d=d;break;default:TwitterService.status.update(e(this),0)}return d};System.addKeyBindingHandler(40,2,function(){TwitterService.status.update(":earthquake",0)})})();AzureaUtil.mixin(AzureaVim.commands_list,{delay:"delay","\u3067\u3041\uff59":"delay"});
(function(){function e(h,d,n){Http.postRequestAsync("http://twitdelay.appspot.com/api/post","user_id="+TwitterService.currentUser.id+"&api_key="+AzureaUtil.db.get("DelayTwitDelayApiKey")+"&status="+h+"&at="+d,false,n)}AzureaUtil.db.get("DelayUseTwitDelay")&&AzureaUtil.db.set("DelayUseTwitDelay","0");AzureaVim.prototype.delay=function(){var h,d;if(h=this.command[1].match(/^(?:(?:(\d{4})-)?(\d{1,2})-(\d{1,2}) )?(\d{1,2}):(\d{1,2})(?::(\d{1,2}))?$/)){d=new Date;h[1]&&d.setFullYear(h[1]);h[2]&&d.setMonth(h[2]-
1);h[3]&&d.setDate(h[3]);d.setHours(h[4]);d.setMinutes(h[5]);d.setSeconds(0);h[6]&&d.setSeconds(h[6]);this.command[1]=d.getTime();h=2}else{this.command[1]=(new Date).getTime()+(this.command[1]-0);h=1}this.command[2]=this.command.slice(2).join(" ");if(AzureaUtil.db.get("DelayUseTwitDelay")){d=new Date(this.command[1]);e(this.command[2],d.getUTCDate()+" "+d.getUTCMonth()+" "+d.getUTCFullYear()+" "+d.getUTCHours()+":"+d.getUTCMinutes()+":"+d.getUTCSeconds()+" +0000",function(){})}else h===1?System.setTimeout(function(n){return function(){TwitterService.status.update(n.command[2],
n.status_id)}}(this),this.command[1]-(new Date).getTime()):AzureaUtil.time.setTimeevent('function() {TwitterService.status.update("'+this.command[2]+'", "'+this.status_id+'");}',this.command[1])}})();AzureaUtil.mixin(AzureaVim.codelist,{});System.addKeyBindingHandler(67,2,function(e){e=TwitterService.status.get(e).text;System.clipboard=e;AzureaUtil.yank.set(null,e)});AzureaUtil.mixin(AzureaVim.commands_list,{notify:"notify"});
(function(){function e(l,j){j=j||"";if(l){k=RegExp(l,j);AzureaUtil.db.set("NotifyPattern",l);AzureaUtil.db.set("NotifyPatternOption",j)}else k=null;return k}function h(){function l(s){var x,b=s.match(/^\/(.*)\/([a-zA-Z]*)$/);if(b){s=b[1];x=b[2].toLowerCase()}return[s,x]}var j,g;switch(h.c1[this.command[1]]){case "pattern":if(j=this.command.slice(2).join(" "))j=l(j);else{j=AzureaUtil.db.get("NotifyPattern");g=AzureaUtil.db.get("NotifyPatternOption");j=l(System.inputBox("tweet\u306b\u30de\u30c3\u30c1\u3055\u305b\u308b\u6b63\u898f\u8868\u73fe",
g?"/"+j+"/"+g:j,false))}g=j[1];j=j[0];e(j,g);break;case "when":j=h.c2[this.command[2]];if(!j)throw Error("plugins/notify: No such option as NotifyWhen "+this.command[2]);m[j]=(this.command[3]||System.inputBox("NotifyWhen"+j,m[j],true))==="0"?"0":"1";AzureaUtil.db.set("NotifyWhen"+j,m[j]);break;case "growl":AzureaUtil.db.set("NotifyUseGrowl",(this.command[2]||System.inputBox("NotifyUseGrowl",AzureaUtil.db.get("NotifyUseGrowl"),true))==="0"?"0":"1")}}var d=AzureaUtil.db.get("NotifyPattern"),n=AzureaUtil.db.get("NotifyPatternOption"),
k=null,m={Faved:AzureaUtil.db.get("NotifyWhenFaved"),Mention:AzureaUtil.db.get("NotifyWhenMention"),Matched:AzureaUtil.db.get("NotifyWhenMatched")};if(d)k=RegExp(d,n);h.c1={pattern:"pattern",when:"when",growl:"growl",gntp:"growl"};h.c2={faved:"Faved",fav:"Faved",f:"Faved",mention:"Mention",reply:"Mention",r:"Mention","@":"Mention",matched:"Matched",match:"Matched",m:"Matched"};AzureaVim.prototype.notify=h;TwitterService.addEventListener("receiveFavorite",function(l,j,g){m.Faved&&AzureaUtil.notify("Favs@"+
l.screen_name+": "+g.text,"Favs - AzureaVim",l.profile_image_url,false)});TwitterService.addEventListener("preFilterProcessTimelineStatus",function(l){var j=m,g=l.text;l=l.user;j.Mention&&g.indexOf(TwitterService.currentUser.screen_name)!==-1&&AzureaUtil.notify("Mention@"+l.screen_name+": "+g,"Mention - AzureaVim",l.profile_image_url,false);j.Matched&&k&&k.test(g)&&AzureaUtil.notify("Matches@"+l.screen_name+": "+g,"Matched - AzureaVim",l.profile_image_url,false)})})();
AzureaUtil.mixin(AzureaVim.commands_list,{tumblr:"tumblr","\u3064\uff4d\uff42\uff4c\uff52":"tumblr"});
(function(){function e(a,f){Http.postRequestAsync("https://www.tumblr.com/api/authenticate","email="+a+"&password="+f,false,function(t){g=200<=t.statusCode||t.statusCode<300?true:false})}function h(a,f,t,i,p,o){function v(r){var w,u=[];for(w in r)r.hasOwnProperty(w)&&u.push(w+"="+encodeURI(r[w]));return u.join("&")}Http.postRequestAsync("https://www.tumblr.com/api/write","email="+a+"&password="+f+"&type="+t+"&"+v(i)+(p?"&"+v(p):""),false,o)}function d(a){if(a.user.protected_)throw Error("plugins/tumblr: "+
a.user.screen_name+" is protected_.");else h(k,m,"quote",{quote:a.text,source:'<a href="http://twitter.com/'+a.user.screen_name+"/status/"+a.id+'">Twitter/@'+a.user.name+": </a>"},{generator:"AzureaVim",tags:j},function(f){if(f.statusCode<200&&300<=f.statusCode)throw Error("plugins/tumblr: Cannot create post. (statusCode="+f.statusCode+")");})}function n(){var a;switch(n.c1[this.command[1]]){case "when":a=n.c2[this.command[2]];if(!a)throw Error("plugins/tumblr: No such option as TumblrWhen "+this.command[2]);
l[a]=(this.command[3]||System.inputBox("TumblrWhen"+a,l[a],true))==="1"?"1":"0";AzureaUtil.db.set("TumblrWhen"+a,l[a]);l.Favorite==="1"?s("postCreateFavorite",d):x("postCreateFavorite",d);l.Retweet==="1"?b("postCreateRetweet",d):c("postCreateRetweet",d);break;case "email":k=this.command[2]||System.inputBox("TumblrEmail",k,true);AzureaUtil.db.set("TumblrEmail",k);e(k,m);break;case "password":m=this.command[2]||System.inputBox("TumblrPassword",m,true);AzureaUtil.db.set("TumblrPassword",m);e(k,m);break;
case "tags":j=this.command[2]||System.inputBox("TumblrTags",j,false);AzureaUtil.db.set("TumblrTags",j);break;default:if(!g)throw Error("plugins/tumblr: Authenticate your email & password.");d(this.status)}}var k=AzureaUtil.db.get("TumblrEmail"),m=AzureaUtil.db.get("TumblrPassword"),l={Favorite:AzureaUtil.db.get("TumblrWhenFavorite")||"0",Retweet:AzureaUtil.db.get("TumblrWhenRetweet")||"0"},j=AzureaUtil.db.get("TumblrTags"),g=false,s=AzureaUtil.favorite.addEventListener,x=AzureaUtil.favorite.removeEventListener,
b=AzureaUtil.retweet.addEventListener,c=AzureaUtil.retweet.removeEventListener;e(k,m);l.Favorite==="1"&&s("postCreateFavorite",d);l.Retweet==="1"&&b("postRetweetFavorite",d);n.c1={when:"when",email:"email",password:"password",tags:"tags",tag:"tags"};n.c2={favorite:"Favorite",fav:"Favorite",f:"Favorite",retweet:"Retweet",rt:"Retweet"};AzureaVim.prototype.tumblr=n})();
