// ==AzureaScript==
// @name AzureaVim
// @author http://c4se.sakura.ne.jp/profile.html
// @scriptUrl https://github.com/ne-sachirou/AzureaVim/raw/master/js/
// @date 2011-04-04
// @license MIT License
// ==/AzureaScript==
AzureaUtil={mixin:{},ApiProxy:{},db:{},event:{},time:{},template:{},yank:{},notify:{}};
(function(){function c(b,d,k){var n;if(k==null)k=true;for(n in d)if(k||typeof b[n]==="undefined")b[n]=d[n]}function e(b,d){System.settings.setValue("user.AzureaVim",b,encodeURIComponent(d));i[b]=d}function a(b){i[b]||(i[b]=decodeURIComponent(System.settings.getValue("user.AzureaVim",b)));return i[b]}function g(b){System.settings.setValue("user.AzureaVim",b,"");delete i[b]}function f(b,d){for(var k=o[b],n=-1;k[++n];)k[n]===d&&k.splice(n,1);k.push(d)}function l(){var b=(new Date).getTime(),d;for(d in t)if(t[d][0]<=
b){t[d][1]();delete t[d]}for(d in x)if(x[d][0]<=b){x[d][0]=b+x[d][2];x[d][1]()}for(d in timeevent_list)if(timeevent_list[d][0]<=b){timeevent_list[d][1]();g("TimeEvent"+timeevent_list[d][2]);delete timeevent_list[d]}}function h(b){System.isActive?System.showNotice(b):System.showMessage(b,b,1048576)}function w(b,d,k,n){b={title:b,text:d,sticky:n?"on":null};b[/^https?:\/\/./.test(k)?"icon_uri":"twitter_screen_name"]=k;notify_proxy.submit(null,b,function(u){try{var m=JSON.parse(u.body);m.error&&h(m.request.text)}catch(j){h(j.message+
u.body)}})}JSON={};(function(){function b(q){return q<10?"0"+q:q}function d(q){u.lastIndex=0;return u.test(q)?'"'+q.replace(u,function(A){var s=r[A];return typeof s==="string"?s:"\\u"+("0000"+A.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+q+'"'}function k(q,A){var s,y,B,D,C=m,z,p=A[q];if(p&&typeof p==="object"&&typeof p.toJSON==="function")p=p.toJSON(q);if(typeof v==="function")p=v.call(A,q,p);switch(typeof p){case "string":return d(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";m+=j;z=[];if(Object.prototype.toString.apply(p)==="[object Array]"){D=p.length;for(s=0;s<D;s+=1)z[s]=k(s,p)||"null";B=z.length===0?"[]":m?"[\n"+m+z.join(",\n"+m)+"\n"+C+"]":"["+z.join(",")+"]";m=C;return B}if(v&&typeof v==="object"){D=v.length;for(s=0;s<D;s+=1)if(typeof v[s]==="string"){y=v[s];if(B=k(y,p))z.push(d(y)+(m?": ":":")+B)}}else for(y in p)if(Object.prototype.hasOwnProperty.call(p,y))if(B=k(y,p))z.push(d(y)+(m?": ":":")+B);B=z.length===0?"{}":m?"{\n"+m+z.join(",\n"+
m)+"\n"+C+"}":"{"+z.join(",")+"}";m=C;return B}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var n=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
u=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,j,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;if(typeof JSON.stringify!=="function")JSON.stringify=function(q,A,s){var y;j=m="";if(typeof s==="number")for(y=0;y<s;y+=1)j+=" ";else if(typeof s==="string")j=s;if((v=A)&&typeof A!=="function"&&(typeof A!=="object"||typeof A.length!=="number"))throw Error("JSON.stringify");return k("",
{"":q})};if(typeof JSON.parse!=="function")JSON.parse=function(q,A){function s(B,D){var C,z,p=B[D];if(p&&typeof p==="object")for(C in p)if(Object.prototype.hasOwnProperty.call(p,C)){z=s(p,C);if(z!==undefined)p[C]=z;else delete p[C]}return A.call(B,D,p)}var y;q=String(q);n.lastIndex=0;if(n.test(q))q=q.replace(n,function(B){return"\\u"+("0000"+B.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(q.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){y=eval("("+q+")");return typeof A==="function"?s({"":y},""):y}throw new SyntaxError("JSON.parse");}})();AzureaUtil.mixin=c;var i={};c(AzureaUtil.db,{get:a,set:e,del:g,keys:function(){var b,d=[];for(b in i)match.test(b)&&d.push(b);return d}});var o={PreProcessTimelineStatuses:[],PreProcessTimelineStatus:[],PreFilterProcessTimelineStatus:[],PostFilterProcessTimelineStatus:[],PostProcessTimelineStatus:[],PostProcessTimelineStatuses:[],PreSendUpdateStatus:[],
PostSendUpdateStatus:[],ReceiveFavorite:[]};c(AzureaUtil.event,{PreProcessTimelineStatuses:o.PreProcessTimelineStatuses,PreProcessTimelineStatus:o.PreProcessTimelineStatus,PreFilterProcessTimelineStatus:o.PreFilterProcessTimelineStatus,PostFilterProcessTimelineStatus:o.PostFilterProcessTimelineStatus,PostProcessTimelineStatus:o.PostProcessTimelineStatus,PostProcessTimelineStatuses:o.PostProcessTimelineStatuses,PreSendUpdateStatus:o.PreSendUpdateStatus,PostSendUpdateStatus:o.PostSendUpdateStatus,ReceiveFavorite:o.ReceiveFavorite,
addEventListener:f,removeEventListener:function(b,d){for(var k=o[b],n=-1;k[++n];)if(k[n]===d){k.splice(n,1);break}}});var t={},x={};timeevent_list=function(){for(var b={},d,k=-1;d=a("TimeEvent"+ ++k);)b[d.substring(0,d.indexOf(":"))]=[d.substring(d.indexOf(":")+1,d.indexOf("|"))-0,eval("(function(){return "+d.substring(d.indexOf("|")+1)+"})()"),k];return b}();f("PreProcessTimelineStatus",l);f("PostSendUpdateStatus",l);f("ReceiveFavorite",l);c(AzureaUtil.time,{setTimeout:function(b,d){var k=Math.floor(Math.random()*
(new Date).getTime()).toString(36);t[k]=[(new Date).getTime()+d,b];return k},clearTimeout:function(b){delete t[b]},setInterval:function(b,d){var k=Math.floor(Math.random()*(new Date).getTime()).toString(36);timeinterval_list[k]=[(new Date).getTime()+d,b,d];return k},clearInterval:function(b){delete timeinterval_list[b]},setTimeevent:function(b,d){for(var k=Math.floor(Math.random()*(new Date).getTime()).toString(36),n=-1;a("TimeEvent"+ ++n););e("TimeEvent"+n,k+":"+d+"|"+b);timeevent_list[k]=[d,eval("(function(){return "+
b+"})()"),n];return k},clearTimeevent:function(b){g("TimeEvent"+timeevent_list[b][2]);delete timeevent_list[b]}});c(AzureaUtil.template,{expand:function(b,d){function k(j){var r,v,q;if(typeof j==="string"||j instanceof String)r='"'+j.replace('"','\\"')+'"';else if(typeof j==="number"||j instanceof Number)r=j.toString(10);else if(j===true||j===false)r=j;else if(j===null)r="null";else if(typeof j==="undefined")r="void(0)";else if(j instanceof Array){r="[";v=0;for(q=j.length;v<q;++v)r+=k(j[v])+",";r=
r.replace(/,$/,"")+"]"}else{r="{";for(v in j)if(j.hasOwnProperty(v))r+='"'+v+'":'+k(j[v])+",";r=r.replace(/,$/,"")+"}"}return r}var n,u=function(){var j,r="";for(j in d)if(d.hasOwnProperty(j))r+="var "+j+"="+k(d[j])+";";return r}(),m=b.replace(/#{([^}]+?)}/g,function(j,r){return eval("(function(){"+u+"return ("+r+")})()")});m=m.split("#{}");if(m.length===1){n=0;m=m[0]}else{n=m[0].length;m=m.join("")}return{text:m,cursor:n}}});c(AzureaUtil.yank,{get:function(b){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=
""}else b="";return a("Yank"+b)},set:function(b,d){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=""}else b="";e("Yank"+b,d);return d}});AzureaUtil.notify=function(b,d,k,n){var u=System.systemInfo<=2&&a("NotifyUseGrowl");try{u?w(d,b,k,n):h(b)}catch(m){h(b)}}})();function PreProcessTimelineStatus(c){for(var e=AzureaUtil.event.PreProcessTimelineStatus,a=-1;e[++a];)e[a](c)}
function PreFilterProcessTimelineStatus(c){for(var e=AzureaUtil.event.PreFilterProcessTimelineStatus,a=-1,g,f=false;e[++a];){g=e[a](c);f=f||g}return f}function PreSendUpdateStatus(c){for(var e=AzureaUtil.event.PreSendUpdateStatus,a=-1,g,f=false;e[++a];){g=e[a](c);f=f||g}return f}function PostSendUpdateStatus(){for(var c=AzureaUtil.event.PostSendUpdateStatus,e=-1;c[++e];)c[e]()}function ReceiveFavorite(c,e,a){for(var g=AzureaUtil.event.ReceiveFavorite,f=-1;g[++f];)g[f](c,e,a)}AzureaVim={};
(function(){function c(f){var l=TwitterService.status,h=f.in_reply_to_status_id,w=l.get(h);this.item=g;f=this.command_text=f.text.slice(1);var i=[],o,t=/[^\s"]+|\s+|"[^\\"]*(?:\\.[^\\"]*)*"/g;for(f=f.replace(/^\s+|\s+$/g,"");o=t.exec(f);)/^\s/.test(o[0])||i.push(o[0].replace(/^"|"$/g,""));this.command=i;this.status_id=h;this.screen_name=w.user.screen_name;this.status_text=w.text;this.status_urls=[];this.status_hashes=[];this.status_users=[];l.getUrls(h,this.status_urls);l.getHashes(h,this.status_hashes);
l.getUsers(h,this.status_users)}var e={},a,g;System.addKeyBindingHandler(186,0,function(f){selected_view=System.views.currentView;a=selected_view.selectedItemId;g=selected_view.getItem(a);AzureaUtil.yank.set(null,TextArea.text);TextArea.text=":";TextArea.in_reply_to_status_id=f;TextArea.show();TextArea.setFocus();TextArea.cursor=1});System.addContextMenuHandler(":vim",0,function(){var f=System.inputBox("command","",true);AzureaUtil.yank.set(null,f);(new c({text:":"+f,in_reply_to_status_id:System.views.currentView.selectedStatusId})).run()});
AzureaUtil.event.addEventListener("PreSendUpdateStatus",function(f){var l,h=false;try{if(f.text===":"){h=true;AzureaUtil.time.setTimeout(function(){TextArea.text=AzureaUtil.yank.get(null);TextArea.show()},0)}else if(/^(?::|\uff1a)/.test(f.text)){h=true;AzureaUtil.yank.set(null,f.text);l=new c(f);TextArea.text="";TextArea.in_reply_to_status_id=0;l.run()}else AzureaUtil.yank.set(null,f.text)}catch(w){System.alert(w.name+":\n"+w.message);h=true}return h});AzureaVim=c;AzureaVim.commands_list=e;AzureaVim.prototype=
{run:function(){var f=this.command,l=e[this.command[0]];if(l){if(l.indexOf(" ")!==-1){f.shift();f=this.command=l.split(" ").concat(f);l=f[0]}this[l]()}else System.showNotice(":"+f[0]+" command is undefined.")}}})();AzureaUtil.mixin(AzureaVim.commands_list,{unshorten:"unshorten","\u3046\u3093\u3057\u3087\uff52\u3066\uff4e":"unshorten"});
(function(){function c(i){f=i.body.split(", ");f.push("htn.ly")}function e(i){for(var o=f,t=-1,x=false;o[++t];)if(i.indexOf(o[t])!==-1){x=true;break}return x}function a(i,o){function t(j){b=(j=j.header.match(/Location: ([^\n]+)\n/))?j[1]:i;j=j?j[1]:i;return b[i]=j}function x(j){j=/^error/.test(j.body)?i:j.body;return b[i]=j}var b=l,d=i;if(b[i])d=b[i];else if(i.indexOf("htn.to")!==-1)if(o)try{Http.sendRequestAsync(i,false,t)}catch(k){}else try{d=callback_htly(Http.sendRequest(i,false))}catch(n){}else if(e(i))if(o)try{Http.sendRequestAsync("http://untiny.me/api/1.0/extract/?url="+
i+"&format=text",false,x)}catch(u){}else try{d=x(Http.sendRequest("http://untiny.me/api/1.0/extract/?url="+i+"&format=text",false))}catch(m){}return d}function g(i,o){function t(u){u=u.body.match(/<body>([\s\S]*?)<\/body>/m)[1];var m;if(m=u.match(/<!\[CDATA\[([\s\S]*?)\]\]>/m))u=m[1].replace(/<\/(?:p|div|blockquote)>/g,"\n").replace(/<[\s\S]+?>/mg,"");u+="\n"+i;return x[b]=u}var x=h,b=i.match(/^https?:\/\/post\.ly\/(.+)$/)[1],d=i;if(x[b])d=x[b];else if(o)try{Http.sendRequestAsync("http://posterous.com/api/getpost?id="+
b,false,t)}catch(k){}else try{d=t(Http.sendRequest("http://posterous.com/api/getpost?id="+b,false))}catch(n){}return d}var f,l={"http://c4se.tk/":"http://c4se.sakura.ne.jp/"},h={};try{Http.sendRequestAsync("http://untiny.me/api/1.0/services/?format=text",true,c)}catch(w){}AzureaUtil.event.addEventListener("PreProcessTimelineStatus",function(i){i.text=i.text.replace(/https?:\/\/[0-9A-Za-z._\-^~\/&%?]+/g,function(o){return o.indexOf("post.ly")!==-1?g(o,true):a(o,true)})});AzureaVim.prototype.unshorten=
function(){var i=this.status_urls[this.command[1]||0];this.item.text=i.indexOf("post.ly")!==-1?this.status_text.replace(i,g(i,false)):this.status_text.replace(i,a(i,false))};AzureaVim.prototype.unshorten.unshorten=a})();AzureaUtil.mixin(AzureaVim.commands_list,{open:"open",o:"open","\u304a":"open",url:"open url","\u3046\uff52\uff4c":"open url"});
(function(){function c(){var a;switch(c.c1[this.command[1]]){case "status":a="https://twitter.com/"+this.screen_name+"/status/"+this.status_id;break;case "favstar":a="http://favstar.fm/t/"+this.status_id;break;case "favotter":a="http://favotter.net/status.php?id="+this.status_id;break;case "favlook":a="http://favlook.osa-p.net/status.html?status_id="+this.status_id;break;case "twistar":a="http://twistar.cc/"+this.screen_name+"/status/"+this.status_id;break;case "favolog":a="http://favolog.org/"+(this.command[2]||
this.screen_name);break;case "twilog":a="http://twilog.org/"+(this.command[2]||this.screen_name);break;case "user":a="http://twitter.com/"+(this.command[2]||this.screen_name);break;case "url":this.command[2]||(this.command[2]=0);a=this.status_urls[this.command[2]];break;default:a=this.status_urls[0]?this.status_urls[0]:"https://twitter.com/"+this.screen_name+"/status/"+this.status_id}a=a;var g;a=e(a,true);(g=System.getPreviewUrl(a))?System.showPreview(a,g):System.openUrl(a)}var e=AzureaVim.prototype.unshorten?
AzureaVim.prototype.unshorten.unshorten:function(a){return a};c.c1={status:"status",favstar:"favstar",fav:"favstar",f:"favstar",favotter:"favotter",favlook:"favlook",twistar:"twistar",favolog:"favolog",twilog:"twilog",user:"user",u:"user",url:"url"};AzureaVim.prototype.open=c;System.addKeyBindingHandler(190,0,function(a){TwitterService.status.update(":o",a)})})();
AzureaUtil.mixin(AzureaVim.commands_list,{reply:"reply",r:"reply","\uff52":"reply","@":"reply","\uff20":"reply",quotetweet:"reply quote",qt:"reply quote","\uff51\uff54":"reply quote",mrt:"reply mrt","\uff4d\uff52\uff54":"reply mrt"});
(function(){function c(){function e(){TextArea.text=f.text;TextArea.in_reply_to_status_id=a===true?g:0;TextArea.show();TextArea.setFocus();TextArea.cursor=f.cursor}var a=this.command[3]==="true",g=this.status_id,f;if(this.command[1]==="template"){f=AzureaUtil.template.expand(this.command[2],this);Http.sendRequestAsync("http://google.com/",false,e)}else{redirect=this.reply.templates[this.reply.c1[this.command[1]]]||["@#{screen_name} #{}#{status_hashes.length ? ' ' + status_hashes.join(' ') : ''}",
true];if(typeof redirect==="function")redirect=redirect.call(this);this.command=["reply","template",redirect[0],redirect[1]?"true":"false"];this.reply()}}c.c1={template:"template",all:"all",quote:"quote",qt:"quote",mrt:"mrt",masirosiki:"mrt"};c.templates={all:["@#{screen_name + (status_users.length ? ' @' +status_users.join(' @') : '')} #{}",true],quote:["@#{screen_name} #{} RT: #{status_text}",true],mrt:function(){return this.command[2]==="f"||this.command[2]==="fav"||this.command[2]==="favstar"?
["reply","template","#{} MRT: #{'http://favstar.fm/t/' + status_id}","false"]:["reply","template","#{} MRT: #{'http://twitter.com/' + screen_name + '/status/' + status_id}","false"]}};AzureaVim.prototype.reply=c;System.addKeyBindingHandler(82,0,function(e){var a=TwitterService.status.get(e).user.screen_name,g=[];TwitterService.status.getHashes(e,g);TextArea.text="@"+a+" "+(g.length?" "+g.join(" "):"");TextArea.in_reply_to_status_id=e;TextArea.show();TextArea.setFocus();TextArea.cursor=a.length+2})})();
AzureaUtil.mixin(AzureaVim.commands_list,{retweet:"retweet",rt:"retweet","\uff52\uff54":"retweet"});AzureaVim.prototype.retweet=function(){TwitterService.retweet.create(this.status_id)};AzureaUtil.mixin(AzureaVim.commands_list,{settings:"settings",setting:"settings",set:"settings","\u305b\uff54":"settings",get:"settings","\u3052\uff54":"settings"});
AzureaVim.prototype.settings=function(){var c;c=this.command.slice(1).join("");c=c.split("::");c=[c[0]].concat(c[1].split("="));if(/^(?:get|\u3052\uff54)/.test(this.command[0]))c.length=2;if(c[2]){System.settings.setValue(c[0],c[1],c[2]);System.showNotice("Setting done: "+c[0]+"::"+c[1]+"="+c[2])}else System.showNotice("Getting done: "+c[0]+"::"+c[1]+"="+System.settings.getValue(c[0],c[1]))};AzureaUtil.mixin(AzureaVim.commands_list,{shindan:"shindanmaker","\u3057\u3093\u3060\uff4e":"shindanmaker"});
AzureaVim.prototype.shindanmaker=function(){for(var c,e=-1,a=this.unshorten?this.unshorten.unshorten:function(g){return g};c=a(this.status_urls[++e],true);)if(c.match("^http://shindanmaker.com/[0-9]+"))break;if(c)Http.postRequestAsync(c,"u="+encodeURI(this.command[1]||TwitterService.currentUser.screen_name),false,function(g){g.body.match("<textarea.*?>(.*?)</textarea>");TextArea.text=RegExp.$1;TextArea.in_reply_to_status_id=0;TextArea.show();TextArea.setFocus()})};
AzureaUtil.mixin(AzureaVim.commands_list,{translate:"translate",ja:"translate ja","\u3058\u3083":"translate ja"});
AzureaVim.prototype.translate=function(){var c=System.views.currentView,e=c.getItem(c.selectedItemId);this.command[1]||(this.command[1]="ja");Http.sendRequestAsync("https://www.googleapis.com/language/translate/v2?key=AIzaSyCva1yUIFIBRqXOZDJ0nrbGbm0bz3FIksc&q="+encodeURI(this.status_text)+"&target="+this.command[1],false,function(a){if(a.statusCode!==200)throw Error("Google Translate API Error. statusCode is "+a.statusCode+".");e.text=a.body.match(/"translatedText"\s*:\s*"(.*)"/)[1]})};
AzureaUtil.mixin(AzureaVim.commands_list,{view:"view",v:"view",home:"view home","\u307b\u3081":"view home",user:"view user","\u3046\u305b\uff52":"view user"});
AzureaVim.prototype.view=function(){switch(this.view.c1[this.command[1]]){case "home":System.views.openView(0);break;case "mention":System.views.openView(1);break;case "message":System.views.openView(2);break;case "user":System.views.openView(5,this.command[2]||this.screen_name);break;case "search":System.views.openView(4,this.command[2]);break;case "favorite":System.views.openView(3);break;case "match":System.views.openView(6,this.command[2]);break;case "following":System.views.openView(8);break;
case "followers":System.views.openView(9)}};AzureaVim.prototype.view.c1={home:"home",timeline:"home",h:"home",mention:"mention",reply:"mention",r:"mention",m:"mention","@":"mention",message:"message",dm:"message",d:"message",user:"user",u:"user",search:"search",favorite:"favorite",fav:"favorite",f:"favorite",match:"match",following:"following",follow:"following",followers:"followers",follower:"followers",followed:"followers"};
AzureaUtil.mixin(AzureaVim.commands_list,{earthquake:"earthquake",jisin:"earthquake","\u3048\u3042\uff52\uff54\uff48\u304f\u3042\u3051":"earthquake","\u3058\u3057\uff4e":"earthquake"});
(function(){function c(a){var g=AzureaUtil.db.get("EarthquakeMessage");if(a!=null)g=AzureaUtil.template.expand(g,a).text;return g}function e(a){a=a||AzureaUtil.db.get("EarthquakeMessage");AzureaUtil.db.set("EarthquakeMessage",a);return a}AzureaUtil.db.get("EarthquakeMessage")||AzureaUtil.db.set("EarthquakeMessage","\u5730\u9707\u306a\u3046 #{Date()}");AzureaVim.prototype.earthquake=function(){var a;switch(this.command[1]){case "set":if(this.command[2])a=e(this.command[2]);else{a=System.inputBox("\u5730\u9707\u306a\u3046\u6295\u7a3f\u6587",
c(),false);e(a);a=a}a=a;break;default:TwitterService.status.update(c(this),0)}return a};System.addKeyBindingHandler(40,2,function(){TwitterService.status.update(":earthquake",0)})})();AzureaUtil.mixin(AzureaVim.commands_list,{delay:"delay","\u3067\u3041\uff59":"delay"});
(function(){function c(e,a,g){Http.postRequestAsync("http://twitdelay.appspot.com/api/post","user_id="+TwitterService.currentUser.id+"&api_key="+AzureaUtil.db.get("DelayTwitDelayApiKey")+"&status="+e+"&at="+a,false,g)}AzureaUtil.db.get("DelayUseTwitDelay")&&AzureaUtil.db.set("DelayUseTwitDelay","0");AzureaVim.prototype.delay=function(){var e,a;if(e=this.command[1].match(/^(?:(?:(\d{4})-)?(\d{1,2})-(\d{1,2}) )?(\d{1,2}):(\d{1,2})(?::(\d{1,2}))?$/)){a=new Date;e[1]&&a.setFullYear(e[1]);e[2]&&a.setMonth(e[2]-
1);e[3]&&a.setDate(e[3]);a.setHours(e[4]);a.setMinutes(e[5]);a.setSeconds(0);e[6]&&a.setSeconds(e[6]);this.command[1]=a.getTime();e=2}else{this.command[1]=(new Date).getTime()+(this.command[1]-0);e=1}this.command[2]=this.command.slice(2).join(" ");if(AzureaUtil.db.get("DelayUseTwitDelay")){a=new Date(this.command[1]);c(this.command[2],a.getUTCDate()+" "+a.getUTCMonth()+" "+a.getUTCFullYear()+" "+a.getUTCHours()+":"+a.getUTCMinutes()+":"+a.getUTCSeconds()+" +0000",function(){})}else e===1?AzureaUtil.time.setTimeout(function(g){return function(){TwitterService.status.update(g.command[2],
g.status_id)}}(this),this.command[1]-(new Date).getTime()):AzureaUtil.time.setTimeevent('function() {TwitterService.status.update("'+this.command[2]+'", "'+this.status_id+'");}',this.command[1])}})();AzureaUtil.mixin(AzureaVim.codelist,{});System.addKeyBindingHandler(67,2,function(c){c=TwitterService.status.get(c).text;System.clipboard=c;AzureaUtil.yank.set(null,c)});AzureaUtil.mixin(AzureaVim.commands_list,{notify:"notify"});
(function(){function c(l,h){h=h||"";if(l){g=RegExp(l,h);AzureaUtil.db.set("NotifyPattern",l);AzureaUtil.db.set("NotifyPatternOption",h)}else g=null;return g}var e=AzureaUtil.db.get("NotifyPattern"),a=AzureaUtil.db.get("NotifyPatternOption"),g=null,f={faved:AzureaUtil.db.get("NotifyWhenFaved"),mention:AzureaUtil.db.get("NotifyWhenMention"),matched:AzureaUtil.db.get("NotifyWhenMatched")};if(e)g=RegExp(e,a);AzureaVim.prototype.notify=function(){function l(i){var o,t=i.match(/^\/(.*)\/([a-zA-Z]*)$/);
if(t){i=t[1];o=t[2].toLowerCase()}return[i,o]}var h,w;h={faved:"Faved",fav:"Faved",f:"Faved",mention:"Mention",reply:"Mention",r:"Mention","@":"Mention",matched:"Matched",match:"Matched",m:"Matched"};switch({pattern:"pattern",when:"when",growl:"growl",gntp:"growl"}[this.command[1]]){case "pattern":if(h=this.command.slice(2).join(" "))h=l(h);else{h=AzureaUtil.db.get("NotifyPattern");w=AzureaUtil.db.get("NotifyPatternOption");h=l(System.inputBox("tweet\u306b\u30de\u30c3\u30c1\u3055\u305b\u308b\u6b63\u898f\u8868\u73fe",
w?"/"+h+"/"+w:h,false))}w=h[1];h=h[0];c(h,w);break;case "when":h=h[this.command[2]];AzureaUtil.db.set("NotifyWhen"+h,this.command[3]||System.inputBox(h,AzureaUtil.db.get("NotifyWhen"+h),true)?"1":"0");break;case "growl":AzureaUtil.db.set("NotifyUseGrowl",this.command[2]||System.inputBox("NotifyUseGrowl",AzureaUtil.db.get("NotifyUseGrowl"),true)?"1":"0")}};AzureaUtil.event.addEventListener("ReceiveFavorite",function(l,h,w){f.faved&&AzureaUtil.notify("Favs@"+l.screen_name+": "+w.text,"Favs - AzureaVim",
l.profile_image_url,false)});AzureaUtil.event.addEventListener("PreFilterProcessTimelineStatus",function(l){var h=l.text;l=l.user;f.mention&&h.indexOf(TwitterService.currentUser.screen_name)!==-1&&AzureaUtil.notify("Mention@"+l.screen_name+": "+h,"Mention - AzureaVim",l.profile_image_url,false);f.matched&&g&&g.test(h)&&AzureaUtil.notify("Matches@"+l.screen_name+": "+h,"Matched - AzureaVim",l.profile_image_url,false)})})();
