// ==AzureaScript==
// @name AzureaVim
// @author http://c4se.sakura.ne.jp/profile.html
// @scriptUrl https://github.com/ne-sachirou/AzureaVim/raw/master/js/
// @date 2011-04-03
// @license MIT License
// ==/AzureaScript==
AzureaUtil={mixin:{},ApiProxy:{},db:{},event:{},time:{},template:{},yank:{},notify:{}};
(function(){function c(b,d,j){var m;if(j==null)j=true;for(m in d)if(j||typeof b[m]==="undefined")b[m]=d[m]}function f(b,d){System.settings.setValue("user.AzureaVim",b,encodeURIComponent(d));s[b]=d}function a(b){s[b]||(s[b]=decodeURIComponent(System.settings.getValue("user.AzureaVim",b)));return s[b]}function g(b){System.settings.setValue("user.AzureaVim",b,"");delete s[b]}function e(b,d){for(var j=u[b],m=-1;j[++m];)j[m]===d&&j.splice(m,1);j.push(d)}function i(){var b=(new Date).getTime(),d;for(d in z)if(z[d][0]<=
b){z[d][1]();delete z[d]}for(d in D)if(D[d][0]<=b){D[d][0]=b+D[d][2];D[d][1]()}for(d in timeevent_list)if(timeevent_list[d][0]<=b){timeevent_list[d][1]();g("TimeEvent"+timeevent_list[d][2]);delete timeevent_list[d]}}function h(b){System.isActive?System.showNotice(b):System.showMessage(b,b,1048576)}function p(b,d,j,m){b={title:b,text:d,sticky:m?"on":null};b[/^https?:\/\/./.test(j)?"icon_uri":"twitter_screen_name"]=j;notify_proxy.submit(null,b,function(A){try{var n=JSON.parse(A.body);n.error&&h(n.request.text)}catch(k){h(k.message+
A.body)}})}JSON={};(function(){function b(o){return o<10?"0"+o:o}function d(o){A.lastIndex=0;return A.test(o)?'"'+o.replace(A,function(x){var r=q[x];return typeof r==="string"?r:"\\u"+("0000"+x.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+o+'"'}function j(o,x){var r,v,y,C,B=n,w,l=x[o];if(l&&typeof l==="object"&&typeof l.toJSON==="function")l=l.toJSON(o);if(typeof t==="function")l=t.call(x,o,l);switch(typeof l){case "string":return d(l);case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);
case "object":if(!l)return"null";n+=k;w=[];if(Object.prototype.toString.apply(l)==="[object Array]"){C=l.length;for(r=0;r<C;r+=1)w[r]=j(r,l)||"null";y=w.length===0?"[]":n?"[\n"+n+w.join(",\n"+n)+"\n"+B+"]":"["+w.join(",")+"]";n=B;return y}if(t&&typeof t==="object"){C=t.length;for(r=0;r<C;r+=1)if(typeof t[r]==="string"){v=t[r];if(y=j(v,l))w.push(d(v)+(n?": ":":")+y)}}else for(v in l)if(Object.prototype.hasOwnProperty.call(l,v))if(y=j(v,l))w.push(d(v)+(n?": ":":")+y);y=w.length===0?"{}":n?"{\n"+n+w.join(",\n"+
n)+"\n"+B+"}":"{"+w.join(",")+"}";n=B;return y}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var m=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
A=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,n,k,q={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;if(typeof JSON.stringify!=="function")JSON.stringify=function(o,x,r){var v;k=n="";if(typeof r==="number")for(v=0;v<r;v+=1)k+=" ";else if(typeof r==="string")k=r;if((t=x)&&typeof x!=="function"&&(typeof x!=="object"||typeof x.length!=="number"))throw Error("JSON.stringify");return j("",
{"":o})};if(typeof JSON.parse!=="function")JSON.parse=function(o,x){function r(y,C){var B,w,l=y[C];if(l&&typeof l==="object")for(B in l)if(Object.prototype.hasOwnProperty.call(l,B)){w=r(l,B);if(w!==undefined)l[B]=w;else delete l[B]}return x.call(y,C,l)}var v;o=String(o);m.lastIndex=0;if(m.test(o))o=o.replace(m,function(y){return"\\u"+("0000"+y.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(o.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){v=eval("("+o+")");return typeof x==="function"?r({"":v},""):v}throw new SyntaxError("JSON.parse");}})();AzureaUtil.mixin=c;var s={};c(AzureaUtil.db,{get:a,set:f,del:g,keys:function(){var b,d=[];for(b in s)match.test(b)&&d.push(b);return d}});var u={PreProcessTimelineStatuses:[],PreProcessTimelineStatus:[],PreFilterProcessTimelineStatus:[],PostFilterProcessTimelineStatus:[],PostProcessTimelineStatus:[],PostProcessTimelineStatuses:[],PreSendUpdateStatus:[],
PostSendUpdateStatus:[],ReceiveFavorite:[]};c(AzureaUtil.event,{PreProcessTimelineStatuses:u.PreProcessTimelineStatuses,PreProcessTimelineStatus:u.PreProcessTimelineStatus,PreFilterProcessTimelineStatus:u.PreFilterProcessTimelineStatus,PostFilterProcessTimelineStatus:u.PostFilterProcessTimelineStatus,PostProcessTimelineStatus:u.PostProcessTimelineStatus,PostProcessTimelineStatuses:u.PostProcessTimelineStatuses,PreSendUpdateStatus:u.PreSendUpdateStatus,PostSendUpdateStatus:u.PostSendUpdateStatus,ReceiveFavorite:u.ReceiveFavorite,
addEventListener:e,removeEventListener:function(b,d){for(var j=u[b],m=-1;j[++m];)if(j[m]===d){j.splice(m,1);break}}});var z={},D={};timeevent_list=function(){for(var b={},d,j=-1;d=a("TimeEvent"+ ++j);)b[d.substring(0,d.indexOf(":"))]=[d.substring(d.indexOf(":")+1,d.indexOf("|"))-0,eval("(function(){return "+d.substring(d.indexOf("|")+1)+"})()"),j];return b}();e("PreProcessTimelineStatus",i);e("PostSendUpdateStatus",i);e("ReceiveFavorite",i);c(AzureaUtil.time,{setTimeout:function(b,d){var j=Math.floor(Math.random()*
(new Date).getTime()).toString(36);z[j]=[(new Date).getTime()+d,b];return j},clearTimeout:function(b){delete z[b]},setInterval:function(b,d){var j=Math.floor(Math.random()*(new Date).getTime()).toString(36);timeinterval_list[j]=[(new Date).getTime()+d,b,d];return j},clearInterval:function(b){delete timeinterval_list[b]},setTimeevent:function(b,d){for(var j=Math.floor(Math.random()*(new Date).getTime()).toString(36),m=-1;a("TimeEvent"+ ++m););f("TimeEvent"+m,j+":"+d+"|"+b);timeevent_list[j]=[d,eval("(function(){return "+
b+"})()"),m];return j},clearTimeevent:function(b){g("TimeEvent"+timeevent_list[b][2]);delete timeevent_list[b]}});c(AzureaUtil.template,{expand:function(b,d){function j(k){var q,t,o;if(typeof k==="string"||k instanceof String)q='"'+k.replace('"','\\"')+'"';else if(typeof k==="number"||k instanceof Number)q=k.toString(10);else if(k===true||k===false)q=k;else if(k===null)q="null";else if(typeof k==="undefined")q="void(0)";else if(k instanceof Array){q="[";t=0;for(o=k.length;t<o;++t)q+=j(k[t])+",";q=
q.replace(/,$/,"")+"]"}else{q="{";for(t in k)if(k.hasOwnProperty(t))q+='"'+t+'":'+j(k[t])+",";q=q.replace(/,$/,"")+"}"}return q}var m,A=function(){var k,q="";for(k in d)if(d.hasOwnProperty(k))q+="var "+k+"="+j(d[k])+";";return q}(),n=b.replace(/#{([^}]+?)}/g,function(k,q){return eval("(function(){"+A+"return ("+q+")})()")});n=n.split("#{}");if(n.length===1){m=0;n=n[0]}else{m=n[0].length;n=n.join("")}return{text:n,cursor:m}}});c(AzureaUtil.yank,{get:function(b){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=
""}else b="";return a("Yank"+b)},set:function(b,d){if(b){b=b.charAt(0);if(/[0-9A-Za-z]/.test(b))b=""}else b="";f("Yank"+b,d);return d}});AzureaUtil.notify=function(b,d,j,m){var A=System.systemInfo<=2&&a("NotifyUseGrowl");try{A?p(d,b,j,m):h(b)}catch(n){h(b)}}})();function PreProcessTimelineStatus(c){for(var f=AzureaUtil.event.PreProcessTimelineStatus,a=-1;f[++a];)f[a](c)}
function PreFilterProcessTimelineStatus(c){for(var f=AzureaUtil.event.PreFilterProcessTimelineStatus,a=-1,g,e=false;f[++a];){g=f[a](c);e=e||g}return e}function PreSendUpdateStatus(c){for(var f=AzureaUtil.event.PreSendUpdateStatus,a=-1,g,e=false;f[++a];){g=f[a](c);e=e||g}return e}function PostSendUpdateStatus(){for(var c=AzureaUtil.event.PostSendUpdateStatus,f=-1;c[++f];)c[f]()}function ReceiveFavorite(c,f,a){for(var g=AzureaUtil.event.ReceiveFavorite,e=-1;g[++e];)g[e](c,f,a)}AzureaVim={};
(function(){function c(a){var g=TwitterService.status,e=a.in_reply_to_status_id,i=g.get(e);a=this.command_text=a.text.slice(1);var h=[],p,s=/[^\s"]+|\s+|"[^\\"]*(?:\\.[^\\"]*)*"/g;for(a=a.replace(/^\s+|\s+$/g,"");p=s.exec(a);)/^\s/.test(p[0])||h.push(p[0].replace(/^"|"$/g,""));this.command=h;this.status_id=e;this.screen_name=i.user.screen_name;this.status_text=i.text;this.status_urls=[];this.status_hashes=[];this.status_users=[];g.getUrls(e,this.status_urls);g.getHashes(e,this.status_hashes);g.getUsers(e,
this.status_users)}var f={};System.addKeyBindingHandler(186,0,function(a){AzureaUtil.yank.set(null,TextArea.text);TextArea.text=":";TextArea.in_reply_to_status_id=a;TextArea.show();TextArea.setFocus();TextArea.cursor=1});System.addContextMenuHandler(":vim",0,function(){var a=System.inputBox("command","",true);AzureaUtil.yank.set(null,a);(new c({text:":"+a,in_reply_to_status_id:System.views.currentView.selectedStatusId})).run()});AzureaUtil.event.addEventListener("PreSendUpdateStatus",function(a){var g,
e=false;try{if(a.text===":"){e=true;AzureaUtil.time.setTimeout(function(){TextArea.text=AzureaUtil.yank.get(null);TextArea.show()},0)}else if(/^(?::|\uff1a)/.test(a.text)){e=true;AzureaUtil.yank.set(null,a.text);g=new c(a);TextArea.text="";TextArea.in_reply_to_status_id=0;g.run()}else AzureaUtil.yank.set(null,a.text)}catch(i){System.alert(i.name+":\n"+i.message);e=true}return e});AzureaVim=c;AzureaVim.commands_list=f;AzureaVim.prototype={run:function(){var a=this.command,g=f[this.command[0]];if(g){if(g.indexOf(" ")!==
-1){a.shift();a=this.command=g.split(" ").concat(a);g=a[0]}this[g]()}else System.showNotice(":"+a[0]+" command is undefined.")}}})();AzureaUtil.mixin(AzureaVim.commands_list,{unshorten:"unshorten","\u3046\u3093\u3057\u3087\uff52\u3066\uff4e":"unshorten"});
(function(){function c(e){for(var i=AzureaVim.prototype.unshorten.services,h=-1,p=false;i[++h];)if(e.indexOf(i[h])!==-1){p=true;break}return p}function f(e,i){var h=a,p,s=e;if(h[e])s=h[e];else if(e.indexOf("htn.ly")!==-1)if(i)try{Http.sendRequestAsync(e,false,function(d){AzureaVim.prototype.unshorten.cashe[e]=d.header.match(/Location: ([^\n]+)\n/)[1]})}catch(u){}else try{s=(p=Http.sendRequest(e,false).header.match(/Location: ([^\n]+)\n/))?p[1]:e;h[e]=s}catch(z){}else if(c(e))if(i)try{Http.sendRequestAsync("http://untiny.me/api/1.0/extract/?url="+
e+"&format=text",false,function(d){AzureaVim.prototype.unshorten.cashe[e]=/^error/.test(d.body)?e:d.body})}catch(D){}else try{p=Http.sendRequest("http://untiny.me/api/1.0/extract/?url="+e+"&format=text",false).body;s=/^error/.test(p)?e:p;h[e]=s}catch(b){}return s}var a={"http://c4se.tk/":"http://c4se.sakura.ne.jp/"};AzureaUtil.event.addEventListener("PreProcessTimelineStatus",function(e){e.text=e.text.replace(/https?:\/\/[0-9A-Za-z._\-^~\/&%?]+/g,function(i){return f(i,true)})});AzureaVim.prototype.unshorten=
function(){var e=this.status_urls[this.command[1]||0],i=System.views.currentView;i=i.getItem(i.selectedItemId);e=e.indexOf("post.ly")!==-1?void 0:f(e);i.text=e};AzureaVim.prototype.unshorten.services=[];AzureaVim.prototype.unshorten.cashe=a;AzureaVim.prototype.unshorten.unshorten=f;try{Http.sendRequestAsync("http://untiny.me/api/1.0/services/?format=text",true,function(e){AzureaVim.prototype.unshorten.services=e.body.split(", ");AzureaVim.prototype.unshorten.services.push("htn.ly")})}catch(g){}})();
AzureaUtil.mixin(AzureaVim.commands_list,{open:"open",o:"open","\u304a":"open",url:"open url","\u3046\uff52\uff4c":"open url"});
(function(){function c(){var a;switch(c.c1[this.command[1]]){case "status":a="https://twitter.com/"+this.screen_name+"/status/"+this.status_id;break;case "favstar":a="http://favstar.fm/t/"+this.status_id;break;case "favotter":a="http://favotter.net/status.php?id="+this.status_id;break;case "favlook":a="http://favlook.osa-p.net/status.html?status_id="+this.status_id;break;case "twistar":a="http://twistar.cc/"+this.screen_name+"/status/"+this.status_id;break;case "favolog":a="http://favolog.org/"+(this.command[2]||
this.screen_name);break;case "twilog":a="http://twilog.org/"+(this.command[2]||this.screen_name);break;case "user":a="http://twitter.com/"+(this.command[2]||this.screen_name);break;case "url":this.command[2]||(this.command[2]=0);a=this.status_urls[this.command[2]];break;default:a=this.status_urls[0]?this.status_urls[0]:"https://twitter.com/"+this.screen_name+"/status/"+this.status_id}a=a;var g;a=f(a,true);(g=System.getPreviewUrl(a))?System.showPreview(a,g):System.openUrl(a)}var f=AzureaVim.prototype.unshorten?
AzureaVim.prototype.unshorten.unshorten:function(a){return a};c.c1={status:"status",favstar:"favstar",fav:"favstar",f:"favstar",favotter:"favotter",favlook:"favlook",twistar:"twistar",favolog:"favolog",twilog:"twilog",user:"user",u:"user",url:"url"};AzureaVim.prototype.open=c;System.addKeyBindingHandler(190,0,function(a){TwitterService.status.update(":o",a)})})();
AzureaUtil.mixin(AzureaVim.commands_list,{reply:"reply",r:"reply","\uff52":"reply","@":"reply","\uff20":"reply",quotetweet:"reply quote",qt:"reply quote","\uff51\uff54":"reply quote",mrt:"reply mrt","\uff4d\uff52\uff54":"reply mrt"});
(function(){function c(){function f(){TextArea.text=e.text;TextArea.in_reply_to_status_id=a===true?g:0;TextArea.show();TextArea.setFocus();TextArea.cursor=e.cursor}var a=this.command[3]==="true",g=this.status_id,e;if(this.command[1]==="template"){e=AzureaUtil.template.expand(this.command[2],this);Http.sendRequestAsync("http://google.com/",false,f)}else{redirect=this.reply.templates[this.reply.c1[this.command[1]]]||["@#{screen_name} #{}#{status_hashes.length ? ' ' + status_hashes.join(' ') : ''}",
true];if(typeof redirect==="function")redirect=redirect.call(this);this.command=["reply","template",redirect[0],redirect[1]?"true":"false"];this.reply()}}c.c1={template:"template",all:"all",quote:"quote",qt:"quote",mrt:"mrt",masirosiki:"mrt"};c.templates={all:["@#{screen_name + (status_users.length ? ' @' +status_users.join(' @') : '')} #{}",true],quote:["@#{screen_name} #{} RT: #{status_text}",true],mrt:function(){return this.command[2]==="f"||this.command[2]==="fav"||this.command[2]==="favstar"?
["reply","template","#{} MRT: #{'http://favstar.fm/t/' + status_id}","false"]:["reply","template","#{} MRT: #{'http://twitter.com/' + screen_name + '/status/' + status_id}","false"]}};AzureaVim.prototype.reply=c;System.addKeyBindingHandler(82,0,function(f){var a=TwitterService.status.get(f).user.screen_name,g=[];TwitterService.status.getHashes(f,g);TextArea.text="@"+a+" "+(g.length?" "+g.join(" "):"");TextArea.in_reply_to_status_id=f;TextArea.show();TextArea.setFocus();TextArea.cursor=a.length+2})})();
AzureaUtil.mixin(AzureaVim.commands_list,{retweet:"retweet",rt:"retweet","\uff52\uff54":"retweet"});AzureaVim.prototype.retweet=function(){TwitterService.retweet.create(this.status_id)};AzureaUtil.mixin(AzureaVim.commands_list,{settings:"settings",setting:"settings",set:"settings","\u305b\uff54":"settings",get:"settings","\u3052\uff54":"settings"});
AzureaVim.prototype.settings=function(){var c;c=this.command.slice(1).join("");c=c.split("::");c=[c[0]].concat(c[1].split("="));if(/^(?:get|\u3052\uff54)/.test(this.command[0]))c.length=2;if(c[2]){System.settings.setValue(c[0],c[1],c[2]);System.showNotice("Setting done: "+c[0]+"::"+c[1]+"="+c[2])}else System.showNotice("Getting done: "+c[0]+"::"+c[1]+"="+System.settings.getValue(c[0],c[1]))};AzureaUtil.mixin(AzureaVim.commands_list,{shindan:"shindanmaker","\u3057\u3093\u3060\uff4e":"shindanmaker"});
AzureaVim.prototype.shindanmaker=function(){for(var c,f=-1,a=this.unshorten?this.unshorten.unshorten:function(g){return g};c=a(this.status_urls[++f],true);)if(c.match("^http://shindanmaker.com/[0-9]+"))break;if(c)Http.postRequestAsync(c,"u="+encodeURI(this.command[1]||TwitterService.currentUser.screen_name),false,function(g){g.body.match("<textarea.*?>(.*?)</textarea>");TextArea.text=RegExp.$1;TextArea.in_reply_to_status_id=0;TextArea.show();TextArea.setFocus()})};
AzureaUtil.mixin(AzureaVim.commands_list,{translate:"translate",ja:"translate ja","\u3058\u3083":"translate ja"});
AzureaVim.prototype.translate=function(){var c=System.views.currentView,f=c.getItem(c.selectedItemId);this.command[1]||(this.command[1]="ja");Http.sendRequestAsync("https://www.googleapis.com/language/translate/v2?key=AIzaSyCva1yUIFIBRqXOZDJ0nrbGbm0bz3FIksc&q="+encodeURI(this.status_text)+"&target="+this.command[1],false,function(a){if(a.statusCode!==200)throw Error("Google Translate API Error. statusCode is "+a.statusCode+".");f.text=a.body.match(/"translatedText"\s*:\s*"(.*)"/)[1]})};
AzureaUtil.mixin(AzureaVim.commands_list,{view:"view",v:"view",home:"view home","\u307b\u3081":"view home",user:"view user","\u3046\u305b\uff52":"view user"});
AzureaVim.prototype.view=function(){switch(this.view.c1[this.command[1]]){case "home":System.views.openView(0);break;case "mention":System.views.openView(1);break;case "message":System.views.openView(2);break;case "user":System.views.openView(5,this.command[2]||this.screen_name);break;case "search":System.views.openView(4,this.command[2]);break;case "favorite":System.views.openView(3);break;case "match":System.views.openView(6,this.command[2]);break;case "following":System.views.openView(8);break;
case "followers":System.views.openView(9)}};AzureaVim.prototype.view.c1={home:"home",timeline:"home",h:"home",mention:"mention",reply:"mention",r:"mention",m:"mention","@":"mention",message:"message",dm:"message",d:"message",user:"user",u:"user",search:"search",favorite:"favorite",fav:"favorite",f:"favorite",match:"match",following:"following",follow:"following",followers:"followers",follower:"followers",followed:"followers"};
AzureaUtil.mixin(AzureaVim.commands_list,{earthquake:"earthquake",jisin:"earthquake","\u3048\u3042\uff52\uff54\uff48\u304f\u3042\u3051":"earthquake","\u3058\u3057\uff4e":"earthquake"});
(function(){function c(a){var g=AzureaUtil.db.get("EarthquakeMessage");if(a!=null)g=AzureaUtil.template.expand(g,a).text;return g}function f(a){a=a||AzureaUtil.db.get("EarthquakeMessage");AzureaUtil.db.set("EarthquakeMessage",a);return a}AzureaUtil.db.get("EarthquakeMessage")||AzureaUtil.db.set("EarthquakeMessage","\u5730\u9707\u306a\u3046 #{Date()}");AzureaVim.prototype.earthquake=function(){var a;switch(this.command[1]){case "set":if(this.command[2])a=f(this.command[2]);else{a=System.inputBox("\u5730\u9707\u306a\u3046\u6295\u7a3f\u6587",
c(),false);f(a);a=a}a=a;break;default:TwitterService.status.update(c(this),0)}return a};System.addKeyBindingHandler(40,2,function(){TwitterService.status.update(":earthquake",0)})})();AzureaUtil.mixin(AzureaVim.commands_list,{delay:"delay","\u3067\u3041\uff59":"delay"});
(function(){function c(f,a,g){Http.postRequestAsync("http://twitdelay.appspot.com/api/post","user_id="+TwitterService.currentUser.id+"&api_key="+AzureaUtil.db.get("DelayTwitDelayApiKey")+"&status="+f+"&at="+a,false,g)}AzureaUtil.db.get("DelayUseTwitDelay")&&AzureaUtil.db.set("DelayUseTwitDelay","0");AzureaVim.prototype.delay=function(){var f,a;if(f=this.command[1].match(/^(?:(?:(\d{4})-)?(\d{1,2})-(\d{1,2}) )?(\d{1,2}):(\d{1,2})(?::(\d{1,2}))?$/)){a=new Date;f[1]&&a.setFullYear(f[1]);f[2]&&a.setMonth(f[2]-
1);f[3]&&a.setDate(f[3]);a.setHours(f[4]);a.setMinutes(f[5]);a.setSeconds(0);f[6]&&a.setSeconds(f[6]);this.command[1]=a.getTime();f=2}else{this.command[1]=(new Date).getTime()+(this.command[1]-0);f=1}this.command[2]=this.command.slice(2).join(" ");if(AzureaUtil.db.get("DelayUseTwitDelay")){a=new Date(this.command[1]);c(this.command[2],a.getUTCDate()+" "+a.getUTCMonth()+" "+a.getUTCFullYear()+" "+a.getUTCHours()+":"+a.getUTCMinutes()+":"+a.getUTCSeconds()+" +0000",function(){})}else f===1?AzureaUtil.time.setTimeout(function(g){return function(){TwitterService.status.update(g.command[2],
g.status_id)}}(this),this.command[1]-(new Date).getTime()):AzureaUtil.time.setTimeevent('function() {TwitterService.status.update("'+this.command[2]+'", "'+this.status_id+'");}',this.command[1])}})();AzureaUtil.mixin(AzureaVim.codelist,{});System.addKeyBindingHandler(67,2,function(c){c=TwitterService.status.get(c).text;System.clipboard=c;AzureaUtil.yank.set(null,c)});AzureaUtil.mixin(AzureaVim.commands_list,{notify:"notify"});
(function(){function c(i,h){h=h||"";if(i){g=RegExp(i,h);AzureaUtil.db.set("NotifyPattern",i);AzureaUtil.db.set("NotifyPatternOption",h)}else g=null;return g}var f=AzureaUtil.db.get("NotifyPattern"),a=AzureaUtil.db.get("NotifyPatternOption"),g=null,e={faved:AzureaUtil.db.get("NotifyWhenFaved"),mention:AzureaUtil.db.get("NotifyWhenMention"),matched:AzureaUtil.db.get("NotifyWhenMatched")};if(f)g=RegExp(f,a);AzureaVim.prototype.notify=function(){function i(s){var u,z=s.match(/^\/(.*)\/([a-zA-Z]*)$/);
if(z){s=z[1];u=z[2].toLowerCase()}return[s,u]}var h,p;h={faved:"Faved",fav:"Faved",f:"Faved",mention:"Mention",reply:"Mention",r:"Mention","@":"Mention",matched:"Matched",match:"Matched",m:"Matched"};switch({pattern:"pattern",when:"when",growl:"growl",gntp:"growl"}[this.command[1]]){case "pattern":if(h=this.command.slice(2).join(" "))h=i(h);else{h=AzureaUtil.db.get("NotifyPattern");p=AzureaUtil.db.get("NotifyPatternOption");h=i(System.inputBox("tweet\u306b\u30de\u30c3\u30c1\u3055\u305b\u308b\u6b63\u898f\u8868\u73fe",
p?"/"+h+"/"+p:h,false))}p=h[1];h=h[0];c(h,p);break;case "when":h=h[this.command[2]];AzureaUtil.db.set("NotifyWhen"+h,this.command[3]||System.inputBox(h,AzureaUtil.db.get("NotifyWhen"+h),true)?"1":"0");break;case "growl":AzureaUtil.db.set("NotifyUseGrowl",this.command[2]||System.inputBox("NotifyUseGrowl",AzureaUtil.db.get("NotifyUseGrowl"),true)?"1":"0")}};AzureaUtil.event.addEventListener("ReceiveFavorite",function(i,h,p){e.faved&&AzureaUtil.notify("Favs@"+i.screen_name+": "+p.text,"Favs - AzureaVim",
i.profile_image_url,false)});AzureaUtil.event.addEventListener("PreFilterProcessTimelineStatus",function(i){var h=i.text;i=i.user;e.mention&&h.indexOf(TwitterService.currentUser.screen_name)!==-1&&AzureaUtil.notify("Mention@"+i.screen_name+": "+h,"Mention - AzureaVim",i.profile_image_url,false);e.matched&&g&&g.test(h)&&AzureaUtil.notify("Matches@"+i.screen_name+": "+h,"Matched - AzureaVim",i.profile_image_url,false)})})();
