// ==AzureaScript==
// @name AzureaVim
// @author http://c4se.sakura.ne.jp/profile.html
// @scriptUrl https://github.com/ne-sachirou/AzureaVim/raw/master/js/
// @date 2011-03-12
// @license MIT License
// ==/AzureaScript==
AzureaUtil={mixin:{},event:{},time:{},template:{},yank:{}};
(function(){function mixin(hash1,hash2,overwrite){var key;if(overwrite==null)overwrite=true;for(key in hash2)if(overwrite||typeof hash1[key]==="undefined")hash1[key]=hash2[key]}AzureaUtil.mixin=mixin;var events_list={PreProcessTimelineStatuses:[],PreProcessTimelineStatus:[],PreFilterProcessTimelineStatus:[],PostFilterProcessTimelineStatus:[],PostProcessTimelineStatus:[],PostProcessTimelineStatuses:[],PreSendUpdateStatus:[],PostSendUpdateStatus:[],ReceiveFavorite:[]};function addEventListener(eventname,
fun){var listener=events_list[eventname],i=-1;while(listener[++i])if(listener[i]===fun)listener.splice(i,1);listener.push(fun)}function removeEventListener(eventname,fun){var listener=events_list[eventname],i=-1;while(listener[++i])if(listener[i]===fun){listener.splice(i,1);break}}mixin(AzureaUtil.event,{PreProcessTimelineStatuses:events_list.PreProcessTimelineStatuses,PreProcessTimelineStatus:events_list.PreProcessTimelineStatus,PreFilterProcessTimelineStatus:events_list.PreFilterProcessTimelineStatus,
PostFilterProcessTimelineStatus:events_list.PostFilterProcessTimelineStatus,PostProcessTimelineStatus:events_list.PostProcessTimelineStatus,PostProcessTimelineStatuses:events_list.PostProcessTimelineStatuses,PreSendUpdateStatus:events_list.PreSendUpdateStatus,PostSendUpdateStatus:events_list.PostSendUpdateStatus,ReceiveFavorite:events_list.ReceiveFavorite,addEventListener:addEventListener,removeEventListener:removeEventListener});var timeout_list={},interval_list={};function attainSchedule(){var now=
(new Date).getTime(),id;for(id in timeout_list)if(timeout_list[id][0]<=now){timeout_list[id][1]();delete timeout_list[id]}for(id in interval_list)if(interval_list[id][0]<=now){interval_list[id][0]+=interval_list[id][2];interval_list[id][1]()}}addEventListener("PreProcessTimelineStatus",attainSchedule);addEventListener("PostSendUpdateStatus",attainSchedule);addEventListener("ReceiveFavorite",attainSchedule);function setTimeout(fun,ms){var id=Math.floor(Math.random()*(new Date).getTime()).toString(36);
timeout_list[id]=[(new Date).getTime()+ms,fun];return id}function clearTimeout(id){delete timeout_list[id]}function setInterval(fun,ms){var id=Math.floor(Math.random()*(new Date).getTime()).toString(36);timeinterval_list[id]=[(new Date).getTime()+ms,fun,ms];return id}function clearInterval(id){delete timeinterval_list[id]}mixin(AzureaUtil.time,{setTimeout:setTimeout,clearTimeout:clearTimeout,setInterval:setInterval,clearInterval:clearInterval});function expandTemplate(template,view){var cursor,text=
template.replace(/#{([^}]+?)}/g,function(m,figure){with(view)return eval(figure)});text=text.split("#{}");if(text.length===1){cursor=0;text=text[0]}else{cursor=text[0].length;text=text.join("")}return{text:text,cursor:cursor}}mixin(AzureaUtil.template,{expand:expandTemplate});function getYank(name){if(name)name=name.charAt(0);else name="";return System.settings.getValue("user.AzureaVim","Yank"+name)}function setYank(name,text){if(name)name=name.charAt(0);else name="";System.settings.setValue("user.AzureaVim",
"Yank"+name,text);return text}mixin(AzureaUtil.yank,{get:getYank,set:setYank})})();function PreProcessTimelineStatus(status){var listener=AzureaUtil.event.PreProcessTimelineStatus,i=-1;while(listener[++i])listener[i](status)}function PreFilterProcessTimelineStatus(status){var listener=AzureaUtil.event.PreFilterProcessTimelineStatus,i=-1,r,flag=false;while(listener[++i]){r=listener[i](status);flag=flag||r}return flag}
function PreSendUpdateStatus(status){var listener=AzureaUtil.event.PreSendUpdateStatus,i=-1,r,flag=false;while(listener[++i]){r=listener[i](status);flag=flag||r}return flag}function PostSendUpdateStatus(){var listener=AzureaUtil.event.PostSendUpdateStatus,i=-1;while(listener[++i])listener[i]()}function ReceiveFavorite(source,target,target_object){var listener=AzureaUtil.event.ReceiveFavorite,i=-1;while(listener[++i])listener[i](source,target,target_object)}AzureaVim={};
(function(){var azvm_commands_list={};function _focusInput(status_id){AzureaUtil.yank.set(null,TextArea.text);TextArea.text=":";TextArea.in_reply_to_status_id=status_id;TextArea.show();TextArea.setFocus();TextArea.setCursor(1)}function _pearse(text){var command=[],match,regex=/[^\s"]+|\s+|"[^\\"]*(?:\\.[^\\"]*)*"/g;text=text.replace(/^\s+|\s+$/g,"");while(match=regex.exec(text))if(!/^\s/.test(match[0]))command.push(match[0].replace(/^"|"$/g,""));return command}function azvm_AzureaVim(status){var TwitterService_status=
TwitterService.status,status_id=status.in_reply_to_status_id,status_obj=TwitterService_status.get(status_id);this.command_text=status.text.slice(1);this.command=_pearse(this.command_text);this.status_id=status_id;this.screen_name=status_obj.user.screen_name;this.status_text=status_obj.text;this.status_urls=[];this.status_hashes=[];this.status_users=[];TwitterService_status.getUrls(status_id,this.status_urls);TwitterService_status.getHashes(status_id,this.status_hashes);TwitterService_status.getUsers(status_id,
this.status_users)}function azvm_run(){var _my_command=this.command,command=azvm_commands_list[this.command[0]];if(command){if(command.indexOf(" ")!==-1){_my_command.shift();_my_command=this.command=command.split(" ").concat(_my_command);command=_my_command[0]}this[command]()}else System.showNotice(":"+_my_command[0]+" command is undefined.")}System.addKeyBindingHandler(186,0,_focusInput);System.addContextMenuHandler(":vim",0,_focusInput);AzureaUtil.event.addEventListener("PreSendUpdateStatus",function(status){var azvm,
do_notpost=false;try{if(status.text===":"){do_notpost=true;AzureaUtil.time.setTimeout(function(){TextArea.text=AzureaUtil.yank.get(null)},0)}else if(/^(?::|\uff1a)/.test(status.text)){do_notpost=true;azvm=new azvm_AzureaVim(status);TextArea.text="";TextArea.in_reply_to_status_id=0;azvm.run()}}catch(e){System.alert(e.name+":\n"+e.message);do_notpost=true}return do_notpost});AzureaVim=azvm_AzureaVim;AzureaVim.commands_list=azvm_commands_list;AzureaVim.prototype={run:azvm_run}})();
AzureaUtil.mixin(AzureaVim.commands_list,{unshorten:"unshorten","\u3046\u3093\u3057\u3087\uff52\u3066\uff4e":"unshorten"});
(function(){var azvm_unshorten_services=[],azvm_unshorten_cashe={"http://c4se.tk/":"http://c4se.sakura.ne.jp/"};function _isPossibleUnshorten(url){var services=AzureaVim.prototype.unshorten.services,i=-1,is_possible=false;while(services[++i])if(url.indexOf(services[i])!==-1){is_possible=true;break}return is_possible}function _unshorten(url,async){var cashe=azvm_unshorten_cashe,response,result=url;if(_isPossibleUnshorten(url))if(cashe[url])result=cashe[url];else if(async)try{Http.sendRequestAsync("http://untiny.me/api/1.0/extract/?url="+
url+"&format=text",false,function(response){AzureaVim.prototype.unshorten.cashe[url]=/^error/.test(response.body)?url:response.body})}catch(e){}else try{response=Http.sendRequest("http://untiny.me/api/1.0/extract/?url="+url+"&format=text",false);result=/^error/.test(response.body)?url:response.body;cashe[url]=result}catch(e){}return result}function azvm_unshorten(){var url=this.status_urls[this.command[1]||0],unurl=_unshorten(url);System.inputBox(url,unurl,false);return unurl}AzureaUtil.event.addEventListener("PreProcessTimelineStatus",
function(status){status.text=status.text.replace(/https?:\/\/[0-9A-Za-z._\-^~\/&%?]+/g,function(url){return _unshorten(url,true)})});AzureaVim.prototype.unshorten=azvm_unshorten;AzureaVim.prototype.unshorten.services=[];AzureaVim.prototype.unshorten.cashe=azvm_unshorten_cashe;AzureaVim.prototype.unshorten.unshorten=_unshorten;try{Http.sendRequestAsync("http://untiny.me/api/1.0/services/?format=text",true,function(response){AzureaVim.prototype.unshorten.services=response.body.split(", ")})}catch(e){}})();
AzureaUtil.mixin(AzureaVim.commands_list,{open:"open",o:"open","\u304a":"open",url:"open url","\u3046\uff52\uff4c":"open url"});
AzureaVim.prototype.open=function(){var url,c1={status:"status",favstar:"favstar",fav:"favstar",f:"favstar",favotter:"favotter",favlook:"favlook",twistar:"twistar",favolog:"favolog",twilog:"twilog",user:"user",url:"url"},_unshorten=this.unshorten?this.unshorten.unshorten:function(url,async){return url};switch(c1[this.command[1]]){case "status":url="https://twitter.com/"+this.screen_name+"/status/"+this.status_id;break;case "favstar":url="http://favstar.fm/t/"+this.status_id;break;case "favotter":url=
"http://favotter.net/status.php?id="+this.status_id;break;case "favlook":url="http://favlook.osa-p.net/status.html?status_id="+this.status_id;break;case "twistar":url="http://twistar.cc/"+this.screen_name+"/status/"+this.status_id;break;case "favolog":url="http://favolog.org/"+(this.command[2]||this.screen_name);break;case "twilog":url="http://twilog.org/"+(this.command[2]||this.screen_name);break;case "user":url="http://twitter.com/"+(this.command[2]||this.screen_name);break;case "url":if(!this.command[2])this.command[2]=
0;url=_unshorten(this.status_urls[this.command[2]],true);break;default:if(this.status_urls[0])url=_unshorten(this.status_urls[0],true);else url="https://twitter.com/"+this.screen_name+"/status/"+this.status_id;break}System.openUrl(url)};AzureaUtil.mixin(AzureaVim.commands_list,{reply:"reply",r:"reply","\uff52":"reply","@":"reply","\uff20":"reply",quotetweet:"reply quote",qt:"reply quote","\uff51\uff54":"reply quote",mrt:"reply mrt","\uff4d\uff52\uff54":"reply mrt"});
(function(){AzureaVim.prototype.reply=function(){var c1={template:"template",all:"all",quote:"quote",qt:"quote",mrt:"mrt",masirosiki:"mrt"},t;switch(c1[this.command[1]]){case "template":t=AzureaUtil.template.expand(this.command[2],this);Http.sendRequestAsync("http://google.com/",false,new Function("TextArea.text = '"+t.text.replace("'","\\'")+"';"+"TextArea.in_reply_to_status_id = '"+(this.command[3]==="true"?this.status_id:0)+"';"+"TextArea.show();"+"TextArea.setFocus();"+"TextArea.setCursor("+t.cursor+
");"));break;case "all":this.command=["reply","template","@#{screen_name + (status_users.length ? ' @' +status_users.join(' @') : '')} #{}","true"];this.reply();break;case "quote":this.command=["reply","template","@#{screen_name} #{} RT: #{status_text}","true"];this.reply();break;case "mrt":if(this.command[2]==="f"||this.command[2]==="fav"||this.command[2]==="favstar")this.command=["reply","template","#{} MRT: #{'http://favstar.fm/t/' + status_id}","false"];else this.command=["reply","template","#{} MRT: #{'http://twitter.com/' + screen_name + '/status/' + status_id}",
"false"];this.reply();break;default:this.command=["reply","template","@#{screen_name} #{}#{status_hashes.length ? ' ' + status_hashes.join(' ') : ''}","true"];this.reply();break}};function reply(status_id){var status=TwitterService.status.get(status_id),status_user_screen_name=status.user.screen_name,status_hashtags=[];TwitterService.status.getHashes(status_id,status_hashtags);TextArea.text="@"+status_user_screen_name+" "+(status_hashtags.length?" "+status_hashtags.join(" "):"");TextArea.in_reply_to_status_id=
status_id;TextArea.show();TextArea.setFocus();TextArea.setCursor(status_user_screen_name.length+2)}System.addKeyBindingHandler(82,0,reply)})();AzureaUtil.mixin(AzureaVim.commands_list,{retweet:"retweet",rt:"retweet","\uff52\uff54":"retweet"});AzureaVim.prototype.retweet=function(){TwitterService.retweet.create(this.status_id)};AzureaUtil.mixin(AzureaVim.commands_list,{settings:"settings",setting:"settings",set:"settings","\u305b\uff54":"settings",get:"settings","\u3052\uff54":"settings"});
AzureaVim.prototype.settings=function(){var figure,value;figure=this.command.slice(1).join("");figure=figure.split("::");figure=[figure[0]].concat(figure[1].split("="));if(/^(?:get|\u3052\uff54)/.test(this.command[0]))figure.length=2;if(figure[2]){System.settings.setValue(figure[0],figure[1],figure[2]);System.showNotice("Setting done: "+figure[0]+"::"+figure[1]+"="+figure[2])}else System.showNotice("Getting done: "+figure[0]+"::"+figure[1]+"="+System.settings.getValue(figure[0],figure[1]))};
AzureaUtil.mixin(AzureaVim.commands_list,{shindan:"shindanmaker","\u3057\u3093\u3060\uff4e":"shindanmaker"});
AzureaVim.prototype.shindanmaker=function(){var url,i=-1,_unshorten=this.unshorten?this.unshorten.unshorten:function(url){return url};while(url=_unshorten(this.status_urls[++i],true))if(url.match("^http://shindanmaker.com/[0-9]+"))break;if(url)Http.postRequestAsync(url,"u="+encodeURI(this.command[1]||TwitterService.currentUser().screen_name),false,function(response){response.body.match("<textarea.*?>(.*?)</textarea>");TextArea.text=RegExp.$1;TextArea.in_reply_to_status_id=0;TextArea.show();TextArea.setFocus()})};
AzureaUtil.mixin(AzureaVim.commands_list,{translate:"translate",ja:"translate ja","\u3058\u3083":"translate ja"});
AzureaVim.prototype.translate=function(){if(!this.command[1])this.command[1]="ja";Http.sendRequestAsync("https://www.googleapis.com/language/translate/v2?key="+"AIzaSyCva1yUIFIBRqXOZDJ0nrbGbm0bz3FIksc"+"&q="+encodeURI(this.status_text)+"&target="+this.command[1],false,function(response){if(response.statusCode!==200)throw Error("Google Translate API Error. statusCode is "+response.statusCode+".");System.showMessage(response.body.match(/"translatedText"\s*:\s*"(.*)"/)[1],response.body.match(/"detectedSourceLanguage"\s*:\s*"(.*)"/)[1]+
"-> ",0)})};AzureaUtil.mixin(AzureaVim.commands_list,{view:"view",v:"view",home:"view home","\u307b\u3081":"view home",user:"view user","\u3046\u305b\uff52":"view user"});
AzureaVim.prototype.view=function(){var c1={home:"home",timeline:"home",h:"home",mention:"mention",reply:"mention",r:"mention",m:"mention","@":"mention",message:"message",dm:"message",d:"message",user:"user",u:"user",search:"search",favorite:"favorite",fav:"favorite",f:"favorite",match:"match",following:"following",follow:"following",followers:"followers",follower:"followers",followed:"followers"},views=System.apiLevel>=11?System.views:System;switch(c1[this.command[1]]){case "home":views.openTimeline();
break;case "mention":views.openMention();break;case "message":views.openMessage();break;case "user":views.openUserTimeline(this.command[2]||this.screen_name,false);break;case "search":views.openSearch(this.command[2],false);break;case "favorite":views.openFavorite();break;case "match":views.openMatch(this.command[2],false);break;case "following":views.openFollwoing();break;case "followers":views.openFollowers();break;default:break}};
